import re

with open(r'f:\E\Downloads\YUMNA\oshudh-ki-boss.html', 'r', encoding='utf-8') as f:
    content = f.read()

# ══════════════════════════════════════════════════════════════════════
# 1. REMOVE .both-subtitle CSS block
# ══════════════════════════════════════════════════════════════════════
both_css_block = """
/* ── BILINGUAL (BOTH) MODE ── */
.both-subtitle {
  display: block;
  font-size: 0.75em;
  color: rgba(0,0,0,0.45);
  font-weight: 400;
  font-family: var(--font-body);
  margin-top: 2px;
  line-height: 1.4;
}
.warning-banner .both-subtitle,
.med-card-stat .both-subtitle,
.mission-card .both-subtitle,
footer .both-subtitle {
  color: rgba(255,255,255,0.4);
}

"""

content = content.replace(both_css_block, "\n")

# ══════════════════════════════════════════════════════════════════════
# 2. REPLACE THE ENTIRE JS SECTION from language toggle onwards
# ══════════════════════════════════════════════════════════════════════

old_js_marker = "// ── Language toggle ───────────────────────────────────────────────────"
js_start = content.find(old_js_marker)
js_end = content.find("</script>", js_start) + len("</script>")

banglish_js = r"""// ── Language toggle ───────────────────────────────────────────────────
const translations = {
  en: {
    'logo-text': 'Oshudh Ki Boss?',
    'logo-sub': 'Know Your Medicine, Gain Health',
    'n-home': 'Home', 'n-med': 'Medicines', 'n-exp': 'Expiry & Storage',
    'n-safe': 'Safety Tips', 'n-about': 'About Us',
    'mn-home': 'Home', 'mn-med': 'Medicines',
    'mn-exp': 'Expiry & Storage', 'mn-safe': 'Safety Tips',
    'mn-about': 'About Us',
    'hero-tag': 'For the working people of Bangladesh',
    'hero-title-main': 'Oshudh Ki Boss?',
    'hero-sub-bn': 'Know Your Medicine, Gain Health',
    'hero-sub-en': 'Empowering communities through medicine literacy',
    'stat1': 'Medicine without doctor', 'stat2': 'Deaths from AMR (2019)', 'stat3': 'Sleeping pill users',
    'cta-learn': '<i class="fi fi-rr-capsule"></i> <span>Learn About Medicines</span>',
    'cta-tips': '<i class="fi fi-rr-shield-check"></i> <span>Safety Tips</span>',
    'hc1-title': 'Antibiotic Resistance is Growing!',
    'hc1-text': 'Wrong use of antibiotics creates resistant bacteria. In the future, medicines stop working.',
    'hc2-title': 'No Medicine Without Prescription',
    'hc2-text': 'WHO says most medicine in Bangladesh is bought without a doctor\'s advice. This is extremely dangerous.',
    'warn-text': '<strong>Did you know?</strong> Taking medicine incorrectly can damage your liver, kidneys and other vital organs. Stay informed, stay healthy.',
    's1': 'Complete your full antibiotic course',
    's2': 'Check the expiry date before buying',
    's3': 'No sleeping pills without a doctor\'s prescription',
    's4': 'Never use someone else\'s medicine',
    's5': 'Keep medicines away from children',
    's1b': 'Complete your full antibiotic course',
    's2b': 'Check the expiry date before buying',
    's3b': 'No sleeping pills without a doctor\'s prescription',
    's4b': 'Never use someone else\'s medicine',
    's5b': 'Keep medicines away from children',
    'mt-tag': 'Medicine Info',
    'mt-title': 'Correct Use of Common Medicines',
    'mt-desc': 'Learn accurate information about each medicine \u2014 why to take it, how to take it, and when to be cautious.',
    'fa': 'All Medicines', 'fb': 'Antibiotics', 'fc': 'Sleeping Pills',
    'fd': 'Gastric', 'fe': 'Painkillers', 'ff': 'Birth Control',
    'm1-title': 'Antibiotics', 'm1-desc': 'Antibiotics are medicines that fight bacterial infections. But many people take antibiotics for colds or fever \u2014 this is wrong and dangerous. Antibiotics do not work on viruses.',
    'm1t1': 'Never take antibiotics without a doctor\'s prescription',
    'm1t2': 'Complete the full course \u2014 never stop halfway',
    'm1t3': 'Never use someone else\'s antibiotic',
    'm1t4': 'Taking with or after food reduces stomach upset',
    'm1-stat': 'In Bangladesh in 2019, <strong>26,200 people died due to AMR</strong> (Antibiotic Resistance). (WHO / The Business Standard)',
    'm2-title': 'Sleeping Pills',
    'm2-desc': 'Many people use sleeping pills for sleep problems. These are benzodiazepines \u2014 they should only be available with a doctor\'s prescription. They are addictive and affect memory long-term.',
    'm2t1': 'Never start on your own \u2014 Prescription is required',
    'm2t2': 'Do not drive or operate heavy machinery',
    'm2t3': 'Never with alcohol \u2014 extremely dangerous',
    'm2t4': 'Do not stop suddenly \u2014 reduce gradually with doctor\'s advice',
    'm2-stat': 'Approximately <strong>300,000 people in Bangladesh</strong> use sleeping pills or sedatives. (The Daily Star)',
    'm3-title': 'Gastric Medicine',
    'm3-desc': 'Gastric medicine is most commonly used in Bangladesh. These PPI medicines are better not taken long-term. See a doctor if needed.',
    'm3t1': 'Take 20-30 minutes before meals (on empty stomach)',
    'm3t2': 'Do not take without doctor for more than 8 weeks',
    'm3t3': 'Reduce spicy and fried foods',
    'm3t4': 'Do not eat just before sleeping',
    'm3-stat': 'Long-term use causes problems with <strong>Vitamin B12, Magnesium and Calcium</strong> absorption. (Banglajol Medical Journal)',
    'm4-title': 'Painkillers',
    'm4-desc': 'Painkillers are the most commonly used medicines. Paracetamol is generally safe, but in high doses damages the liver. Ibuprofen can cause stomach problems. Taking two painkillers together is dangerous.',
    'm4t1': 'For adults: maximum Paracetamol 500mg \u00d7 4 times daily',
    'm4t2': 'Take Ibuprofen with food \u2014 not on empty stomach',
    'm4t3': 'Do not take two painkillers together',
    'm4t4': 'Do not take for more than 3 days without doctor',
    'm4-stat': 'Paracetamol overdose is one of the leading causes of <strong>acute liver failure</strong> worldwide. Follow the correct dose.',
    'm5-title': 'Birth Control Pills',
    'm5-desc': 'Birth control pills must be taken correctly at the same time every day. Missing one pill reduces effectiveness. Emergency pills should not be used regularly.',
    'm5t1': 'Take at the same time every day \u2014 after breakfast is good',
    'm5t2': 'If one pill is missed, take two the next day and be extra cautious',
    'm5t3': 'Breastfeeding mothers should use a different type of pill',
    'm5t4': 'Consult a doctor or pharmacist before starting',
    'm5-stat': 'When used correctly, OCP is <strong>99%+ effective</strong>. But with incorrect use, effectiveness drops to 91%.',
    'm6-title': 'Antihistamine / Allergy Medicine',
    'm6-desc': 'Used for allergies, sneezing, itching and rashes. Older antihistamines (Chlorpheniramine, Phenergan) cause drowsiness. Many people drive without knowing this \u2014 dangerous!',
    'm6t1': 'Take older antihistamines (Phenergan, Avil) at night',
    'm6t2': 'Newer antihistamines (Cetirizine, Loratadine) cause less drowsiness',
    'm6t3': 'Do not drive after taking them',
    'm6t4': 'Children\'s dose is different from adults \u2014 be careful',
    'm6-stat': 'Many in Bangladesh take <strong>Phenergan or Avil</strong> as a cough medicine \u2014 but it is an antihistamine and sedative.',
    'et-tag': 'Expiry & Storage', 'et-title': 'Medicine Expiry & Proper Storage',
    'et-desc': 'Expired medicine has no benefit, it can even cause harm. If not stored properly, medicine can spoil even before expiry.',
    'eh-title': 'EXP: 07/2027 \u2014 What Does This Mean?',
    'eh-text': 'Every medicine packet has an EXP or Expiry Date. This means the medicine is usable until the last day of that month. After that, the chemical may change and effectiveness decreases.',
    'eh-text2': 'In Bangladesh\'s hot and humid climate, medicine deteriorates even faster. So proper storage is essential.',
    'exp-meaning': 'Do not use after July 2027',
    'before-exp': 'Within expiry', 'after-exp': 'Expired',
    'exp-cards-title': 'Important Expiry Information',
    'ec1-t': 'Where to look?', 'ec1-p': 'Usually on the back of the strip, bottom of the box, or bottle label. "MFG" means manufacturing date, "EXP" means expiry date.',
    'ec2-t': 'What happens if you take expired medicine?', 'ec2-p': 'Some medicines just become less effective, others become toxic. Especially eye drops, liquid antibiotics and insulin are dangerous after expiry. Don\'t take the risk.',
    'ec3-t': 'How to dispose of old medicines?', 'ec3-p': 'Don\'t pour down the drain \u2014 pollutes the environment. Don\'t flush down the toilet. Put in a sealed bag and in the dustbin, or return to a nearby pharmacy.',
    'store-title': 'How to Store Medicines',
    'sc1-t': 'Protect from heat', 'sc1-p': 'Keep most medicines at room temperature (15-25\u00b0C). In Bangladesh\'s heat, keep the medicine cabinet in a cool place. Keep away from direct sunlight.',
    'sc2-t': 'Avoid humidity', 'sc2-p': 'Don\'t keep medicines in the bathroom \u2014 steam damages medicines. Keep in original packaging and tightly closed.',
    'sc3-t': 'Out of children\'s reach', 'sc3-p': 'Children may eat colorful tablets thinking they are candy. Always keep in a locked cabinet or high place.',
    'sc4-t': 'Medicines that need refrigeration', 'sc4-p': 'Insulin, some eye drops and liquid antibiotics need to be refrigerated. Do not freeze. Medicines labeled "Store in Cool Place" can go in the fridge door.',
    'st-tag': 'Safety', 'st-title': 'Golden Rules of Medicine Use',
    'st-desc': 'Following these simple rules can prevent most medicine-related accidents.',
    'sr1-t': 'Don\'t take medicine without doctor\'s advice',
    'sr1-p': 'Everyone\'s body is different. What worked for your neighbour may be dangerous for you. Especially antibiotic, steroid and sleeping pill require a prescription.',
    'sr2-t': 'Don\'t use someone else\'s medicine',
    'sr2-p': 'Even with the same symptoms, the cause may be different. Using someone else\'s medicine can worsen your condition and delay correct diagnosis.',
    'sr3-t': 'Read the label completely',
    'sr3-p': 'Dose, frequency, before or after food \u2014 this information is on the label. If you can\'t read it, ask the pharmacist.',
    'sr4-t': 'Be careful with multiple medicines',
    'sr4-p': 'Taking two medicines together can cause drug interaction. For example, taking Paracetamol with Warfarin (blood thinner) is dangerous. Tell your doctor about all medicines you take.',
    'sr5-t': 'Complete the full antibiotic course',
    'sr5-p': 'Don\'t stop antibiotics just because you feel better. If the doctor gave a 7-day course, take all 7 days. Half a course doesn\'t kill bacteria, it makes them resistant.',
    'sr6-t': 'Ask your pharmacist',
    'sr6-p': 'Pharmacists don\'t just sell medicines \u2014 they are trained professionals. Ask any questions about side effects, dose, or interactions. They are ready to help.',
    'dos-title': 'What To Do', 'donts-title': 'What NOT To Do',
    'do1': 'Follow doctor\'s prescription', 'do2': 'Get pharmacist\'s advice',
    'do3': 'Complete the full medicine course', 'do4': 'Check expiry date before buying',
    'do5': 'Tell doctor if you have side effects', 'do6': 'Store medicines in cool dry place',
    'do7': 'Tell doctor about allergies in advance',
    'dont1': 'Don\'t start antibiotics without doctor', 'dont2': 'Don\'t stop medicine halfway',
    'dont3': 'Don\'t take someone else\'s medicine', 'dont4': 'Don\'t take expired medicine',
    'dont5': 'Don\'t store in bathroom or kitchen', 'dont6': 'Don\'t take too many different medicines',
    'dont7': 'Don\'t leave medicines within children\'s reach',
    'gen-title': 'Generic vs Brand \u2014 What\'s the Difference?',
    'gen-desc': 'The same medicine is sold under different names. The generic name is the name of the core chemical \u2014 it does the same job in all brands.',
    'gc1': 'Paracetamol (Generic)', 'gc1b': 'Napa, Ace, Renova, Tylenol, Panadol', 'gc1c': 'Same medicine, different brand name',
    'gc2': 'Omeprazole (Generic)', 'gc2b': 'Omez, Losec, Prilosec, Seclo', 'gc2c': 'Cheaper generic works just as well',
    'gc3': 'Cetirizine (Generic)', 'gc3b': 'Alatrol, Cetrizin, Zyrtec, Allegra', 'gc3c': 'You can ask pharmacist for generic',
    'fq-title': 'Frequently Asked Questions', 'fq-desc': 'The questions people ask most \u2014 simple answers.',
    'fq1-q': '<span class="faq-badge badge-danger"><i class="fi fi-sr-triangle-warning"></i> Antibiotic</span>Can I stop Antibiotics when I feel better?',
    'fq1-a': 'No, absolutely not. If the doctor gave a 5-day course, take all 5 days even if you feel better after 3. Because 90% of bacteria die in 3 days, but the remaining 10% are the strongest. If you don\'t kill them, antibiotics won\'t work later (Antibiotic Resistance).',
    'fq2-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-capsule"></i> Painkiller</span>Will taking two Painkillers together work better for severe pain?',
    'fq2-a': 'No! Taking two similar painkillers (like two paracetamols, or paracetamol + ibuprofen) together is dangerous. It can seriously damage the liver or stomach. For severe pain, talk to a doctor before increasing the dose.',
    'fq3-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-flower"></i> Birth Pill</span>What to do if I miss a birth control pill?',
    'fq3-a': 'If you remember within 24 hours, take one pill. If more than 24 hours have passed, skip that pill and take the next one at the normal time. But be extra cautious during this time. If two pills are missed, get a doctor\'s advice immediately.',
    'fq4-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-alarm-clock"></i> Expiry</span>Is it safe to take expired medicine in an emergency?',
    'fq4-a': 'Most solid tablets just become less effective \u2014 they don\'t immediately become toxic. But liquid antibiotics, eye drops, insulin and injections can be dangerous when expired. Use fresh medicine wherever possible and don\'t keep expired medicines at home.',
    'fq5-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-comment-alt"></i> Generic</span>If pharmacist gives a different brand, will it work the same?',
    'fq5-a': 'Yes, usually. If the doctor writes Napa but the pharmacist gives Ace or Renova, it does the same job \u2014 because the core chemical is Paracetamol in all of them. These are called Generics. However, for some special medicines (like thyroid, seizure) you should not change brands. Ask the pharmacist if in doubt.',
    'fq6-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-moon"></i> Sleeping Pill</span>Are sleeping pills safe?',
    'fq6-a': 'Sleeping pills are safe short-term with a doctor\'s prescription. But they become addictive long-term (more than 2 weeks). Stopping suddenly causes withdrawal. For a permanent solution to sleep problems, change your lifestyle and get a doctor\'s advice.',
    'fq7-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-heart-rate"></i> Gastric</span>Is it okay to take gastric medicine every day?',
    'fq7-a': 'No, it is not okay to take every day. At most 4-8 weeks when needed. More than that can cause weak bones, reduced Vitamin B12 and kidney problems. Change your lifestyle \u2014 reduce spicy food, eat on time.',
    'fq8-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-head-side-cough"></i> Allergy</span>Can I drive after taking allergy medicine?',
    'fq8-a': 'Older antihistamines (Phenergan, Avil, Chlorpheniramine) cause drowsiness \u2014 driving is dangerous. Newer antihistamines (Cetirizine, Loratadine, Fexofenadine) cause comparatively less drowsiness. But after taking any allergy medicine, assess your own condition before driving.',
    'ab-tag': 'About', 'ab-title': 'The Story Behind This Initiative',
    'founder-name': 'Habeba Hussain', 'founder-role': 'Pharmacy Student & Fellow',
    'ab-p1': 'Most working people in Bangladesh \u2014 garment workers, rickshaw pullers, shopkeepers, domestic workers \u2014 do not know correct information about medicines. They often buy medicine from nearby shops, lacking both time and money to visit a doctor.',
    'ab-p2': 'Studying pharmacy, I saw that these people could avoid many dangers if they just had the right information. Antibiotic resistance, overdose, expired medicine \u2014 these problems are happening simply due to lack of knowledge.',
    'ab-p3': 'This website was created for those people. In simple Bangla, in plain language \u2014 so anyone can understand. There will be QR code posters in local pharmacies \u2014 people can scan and learn while buying medicine.',
    'fel-title': 'Fellowship Program \u2014 Round 2',
    'fel-desc': 'This project was created as part of a Fellowship Program. Goal: Increase medicine awareness among working-class people.',
    'mis-title': 'Our Mission',
    'mp1': 'Providing correct medicine information in simple language',
    'mp2': 'Awareness about antibiotic misuse and resistance',
    'mp3': 'Delivering information directly to pharmacies via QR code',
    'mp4': 'Protecting people from the dangers of expired medicines',
    'mp5': 'Health protection for working and less-educated people',
    'cont-title': 'Contact Us',
    'cont-role': 'Pharmacy Student, Bangladesh',
    'disclaimer-text': 'This website is for awareness only. Always consult a qualified doctor for medical treatment.',
    'qr-cta-title': 'QR Code Poster',
    'qr-cta-desc': 'This poster will be in local pharmacies. Scanning it takes you directly to this website.',
    'qr-btn': '<i class="fi fi-rr-smartphone"></i> View QR Code',
    'qr-title': 'Pharmacy Poster QR Code',
    'qr-desc': 'Scan the QR code below or print it and put it in your pharmacy.',
    'poster-head': '<i class="fi fi-rr-document" style="margin-right:6px;"></i> Poster Text',
    'poster-line1': '<i class="fi fi-rr-capsule" style="margin-right:4px;"></i> Buying medicine?',
    'poster-line2': 'Use it correctly.<br>Scan this QR code and learn for free.',
    'poster-cta': 'Oshudh Ki Boss? | Know Your Medicine, Gain Health',
    'qr-caption': 'Scanning this QR Code takes you directly to this website.',
    'dl-btn': '<i class="fi fi-rr-download"></i> Download QR',
    'print-btn': '<i class="fi fi-rr-print"></i> Print',
    'ft-desc': 'A medicine awareness initiative for the working people of Bangladesh. In simple language, free of charge.',
    'fl1': 'Home', 'fl2': 'Medicines', 'fl3': 'Expiry', 'fl4': 'Safety', 'fl5': 'FAQ',
    'fl6': 'About Us', 'fl7': 'QR Code',
    'ft-disclaimer': '<i class="fi fi-sr-triangle-warning"></i> This website is for awareness purposes only. Always consult a qualified doctor or pharmacist for treatment.',
  },
  bn: {
    'logo-text': 'ওষুধটা কী বস?',
    'logo-sub': 'Know Your Medicine',
    'n-home': 'হোম', 'n-med': 'ওষুধ সমূহ', 'n-exp': 'মেয়াদ ও সংরক্ষণ',
    'n-safe': 'নিরাপত্তা টিপস', 'n-about': 'আমাদের সম্পর্কে',
    'mn-home': 'হোম', 'mn-med': 'ওষুধ সমূহ',
    'mn-exp': 'মেয়াদ ও সংরক্ষণ', 'mn-safe': 'নিরাপত্তা টিপস',
    'mn-about': 'আমাদের সম্পর্কে',
    'hero-tag': 'বাংলাদেশের কর্মজীবী মানুষের জন্য',
    'hero-title-main': 'ওষুধটা কী বস?',
    'hero-sub-bn': 'ওষুধ জানি, স্বাস্থ্য পাই',
    'hero-sub-en': 'Know Your Medicine, Gain Health',
    'stat1': 'ডাক্তার ছাড়া ওষুধ', 'stat2': 'AMR-এ মৃত্যু (২০১৯)', 'stat3': 'ঘুমের ওষুধ ব্যবহারকারী',
    'cta-learn': '<i class="fi fi-rr-capsule"></i> <span>ওষুধ সম্পর্কে জানুন</span>',
    'cta-tips': '<i class="fi fi-rr-shield-check"></i> <span>নিরাপত্তা টিপস</span>',
    'hc1-title': 'Antibiotic Resistance বাড়ছে!',
    'hc1-text': 'ভুলভাবে antibiotic ব্যবহারে শরীরে resistant bacteria তৈরি হয়। ফলে ভবিষ্যতে ওষুধ কাজ করে না।',
    'hc2-title': 'Prescription ছাড়া ওষুধ নয়',
    'hc2-text': 'WHO বলছে, বাংলাদেশে অধিকাংশ ওষুধ doctor এর পরামর্শ ছাড়াই কেনা হয়। এটি অত্যন্ত বিপজ্জনক।',
    'warn-text': '<strong>জানেন কি?</strong> ভুলভাবে ওষুধ খেলে liver, kidney ও শরীরের গুরুত্বপূর্ণ অঙ্গের ক্ষতি হতে পারে। সচেতন হন, সুস্থ থাকুন।',
    's1': 'Antibiotic সম্পূর্ণ course শেষ করুন',
    's2': 'Expiry date দেখে ওষুধ কিনুন',
    's3': 'Doctor এর prescription ছাড়া ঘুমের ওষুধ নয়',
    's4': 'অন্যের ওষুধ নিজে খাবেন না',
    's5': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    's1b': 'Antibiotic সম্পূর্ণ course শেষ করুন',
    's2b': 'Expiry date দেখে ওষুধ কিনুন',
    's3b': 'Doctor এর prescription ছাড়া ঘুমের ওষুধ নয়',
    's4b': 'অন্যের ওষুধ নিজে খাবেন না',
    's5b': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    'mt-tag': 'ওষুধ তথ্য',
    'mt-title': 'সাধারণ ওষুধের সঠিক ব্যবহার',
    'mt-desc': 'প্রতিটি ওষুধ সম্পর্কে সঠিক তথ্য জানুন — কী কারণে খাবেন, কীভাবে খাবেন, এবং কখন সতর্ক হবেন।',
    'fa': 'সব ওষুধ', 'fb': 'Antibiotics', 'fc': 'ঘুমের ওষুধ',
    'fd': 'গ্যাস্ট্রিক', 'fe': 'Painkillers', 'ff': 'Birth Control',
    'm1-title': 'অ্যান্টিবায়োটিক',
    'm1-desc': 'Antibiotic holo emon oshudh ja bacteriar songkromon dur kore. Kintu onek e sordi-jore o antibiotic khan — eta bhul ebong bipodjonok. Virus-e antibiotic kaj kore na.',
    'm1t1': 'Doctor er poramorsho chhara antibiotic khabenna',
    'm1t2': 'Shompurno course shesh korun — majhpothe bondho korbenna',
    'm1t3': 'Onner antibiotic nije bybohar korbenna',
    'm1t4': 'Khabarer shathe ba pore khele peter shomossa kome',
    'm1-stat': 'বাংলাদেশে ২০১৯ সালে <strong>AMR-এর কারণে ২৬,২০০ জন</strong> মারা গেছেন। (WHO / The Business Standard)',
    'm2-title': 'ঘুমের ওষুধ',
    'm2-desc': 'Ghumer shomossay onek e ei oshudh bybohar koren. Egulo benzodiazepine shrenir — shudhumatro doctor er prescription e paowa uchit. Era addictive ebong dirghomeyade smritishokti te probhab fele.',
    'm2t1': 'Kokhono nije theke shuru korbenna — Prescription abosshok',
    'm2t2': 'Gari chalabenna ba bhari kaj korbenna',
    'm2t3': 'Alcohol er shathe ekdom noy — marattok bipod',
    'm2t4': 'Hothat bondho na kore doctor er poramorshe dhire dhire koman',
    'm2-stat': 'বাংলাদেশে প্রায় <strong>৩ লাখ মানুষ</strong> ঘুমের ওষুধ বা sedative ব্যবহার করেন। (The Daily Star)',
    'm3-title': 'গ্যাস্ট্রিকের ওষুধ',
    'm3-desc': 'Bangladesh e gastric er oshudh shobcheye beshi khawa hoy. Ei PPI (Proton Pump Inhibitor) oshudh dirghomeyade na khawai bhalo. Proyojone doctor dekhan.',
    'm3t1': 'Khabar age (khali pete) 20-30 minute age khan',
    'm3t2': 'Dirghomeyade (8 shoptaher beshi) doctor chhara noy',
    'm3t3': 'Moshladar o bhaja khabar koman',
    'm3t4': 'Rate showar age khabenna',
    'm3-stat': 'দীর্ঘমেয়াদী ব্যবহারে <strong>Vitamin B12, Magnesium ও Calcium</strong> শোষণে সমস্যা হয়। (Banglajol Medical Journal)',
    'm4-title': 'ব্যথার ওষুধ',
    'm4-desc': 'Painkiller shobcheye beshi bybohorito oshudh. Paracetamol shadharonoto nirapod, kintu beshi dose-e liver khoti kore. Ibuprofen pet kharap korte pare. Duto painkiller ekshathe khawa bipodjonok.',
    'm4t1': 'Praptoboyosker jonno Paracetamol shorbochcho 500mg x 4 bar dine',
    'm4t2': 'Ibuprofen khabarer shathe khan — khali pete noy',
    'm4t3': 'Duto painkiller ekshathe khabenna',
    'm4t4': '3 diner beshi doctor chhara noy',
    'm4-stat': 'Paracetamol overdose bisshwer onnotomo prodhan <strong>acute liver failure-er karon</strong>. Shothik dose mene cholun.',
    'm5-title': 'Birth Control Pill',
    'm5-desc': 'Birth control pill shothikbhabe protidin eki shomoy e khete hoy. Ekti pill miss hole effectiveness kome jay. Emergency pill niyomito bybohar kora uchit noy.',
    'm5t1': 'Protidin eki shomoy e khan — sokaler nastar pore bhalo',
    'm5t2': 'Ekti pill bad porle porer din duto khan ebong otirrikto shotorko thakun',
    'm5t3': 'Breast milk khaowano mayera bhinno dhoroner pill bybohar korun',
    'm5t4': 'Shuru korar age doctor ba pharmacist er poramorsho nin',
    'm5-stat': 'Shothikbhabe bybohar korle OCP <strong>99%+ effective</strong>. Kintu bhul bybohar e effectiveness 91%-e neme ashe.',
    'm6-title': 'Antihistamine / Allergy oshudh',
    'm6-desc': 'Allergy, hachi, chulkani, rash er jonno ei oshudh bybohar hoy. Purono antihistamine (Chlorpheniramine, Phenergan) ghumobhab shrishti kore. Onek e eta na jene gari chalan — bipodjonok!',
    'm6t1': 'Purono antihistamine (Phenergan, Avil) rate nin',
    'm6t2': 'Notun antihistamine (Cetirizine, Loratadine) kom ghumobhab dey',
    'm6t3': 'Khawar por gari chalabenna',
    'm6t4': 'Bacchader dose boro manusher cheye alada — sabdhan',
    'm6-stat': 'Bangladesh e onek e <strong>Phenergan ba Avil</strong> kashir oshudh hishebe khan — kintu eta antihistamine ebong sedative.',
    'et-tag': 'Meyad & Storage', 'et-title': 'Oshudher meyad o shothik shongrokkhon',
    'et-desc': 'Expired oshudh khele kono upokar nei, boroncho khoti hote pare. Shothikbhabe shongrokkhon na korle oshudh age i noshto hoy.',
    'eh-title': 'EXP: 07/2027 — Er mane ki?',
    'eh-text': 'Protiti oshudher packet e EXP ba Expiry Date lekha thake. Ei tarikh mane holo — ei masher shesh din porjonto oshudh ti byboharjojjo. Tarpor theke oshudher chemical bodle jete pare ebong effectiveness kome jay.',
    'eh-text2': 'Bangladesh er gorom o ardro abohawaye oshudh aro druto noshto hoy. Tai shothik jaygay rakha joruri.',
    'exp-meaning': 'July 2027 er por bybohar korbenna',
    'before-exp': 'Meyader moddhe', 'after-exp': 'Expired',
    'exp-cards-title': 'Meyad shongkranto important tothho',
    'ec1-t': 'Kothay dekhben?', 'ec1-p': 'Oshudher strip er pichhone, box er niche ba bottle er label e shadharonoto EXP ba Exp. Date lekha thake. "MFG" mane manufacturing date, "EXP" mane expiry date.',
    'ec2-t': 'Expired oshudh khele ki hoy?', 'ec2-p': 'Kichu oshudh shudhu kom effective hoy, abar kichu toxic hoye jay. Bisheshoto eye drops, liquid antibiotics o insulin expired hole bipodjonok. Risk newa uchit noy.',
    'ec3-t': 'Purono oshudh felbenna kibhabe?', 'ec3-p': 'Pani te felbenna — poribesh dushito hoy. Toilet e flush korbenna. Ekti sealed bag e bhore dustbin e felun, othoba kacher pharmacy te joma din.',
    'store-title': 'Oshudh kibhabe store korben',
    'sc1-t': 'Temperature theke bachan', 'sc1-p': 'Beshirbhag oshudh room temperature (15-25°C)-e rakhun. Bangladesh er gorome oshudher cabinet thanda jaygay rakhun. Direct sunlight theke dure rakhun.',
    'sc2-t': 'Humidity eiye cholun', 'sc2-p': 'Bathroom e oshudh rakhbenna — bhap oshudh noshto kore. Original packaging e rakhun ebong tight kore bondho rakhun.',
    'sc3-t': 'Bacchader nagler baire', 'sc3-p': 'Bacchara rangin tablet dekhle candy mone kore kheye felte pare. Shobshomoy lock kora cabinet e ba unchu jaygay rakhun.',
    'sc4-t': 'Fridge e rakhar oshudh', 'sc4-p': 'Insulin, kichu eye drops o liquid antibiotic fridge e rakhte hoy. Freeze korbenna. Je shob oshudhe "Store in Cool Place" lekha shegulo fridge er dorojay rakhun.',
    'st-tag': 'Safety', 'st-title': 'Oshudh byoboharer golden rules',
    'st-desc': 'Ei simple niymgulo mene cholle odhikangsh oshudh-jonito durghotona erano shombhob.',
    'sr1-t': 'Doctor er poramorsho chhara oshudh khabenna',
    'sr1-p': 'Protiti manusher shorir alada. Apnar neighbour er je oshudh kaj koreche, sheta apnar jonno bipodjonok hote pare. Bisheshoto antibiotic, steroid o sleeping pill er khetre prescription abosshok.',
    'sr2-t': 'Onner oshudh bybohar korbenna',
    'sr2-p': 'Eki roger symptom thakleo karon bhinno hote pare. Onner oshudh nile apnar rog barte pare ebong shothik diagnosis derir hobe.',
    'sr3-t': 'Label shompurno porun',
    'sr3-p': 'Dose, kotbar khaben, khabarer age na pore — ei tothho gulo label e thake. Porte na parle pharmacist ke jiggesh korun.',
    'sr4-t': 'Ekshathe onek oshudh shotorkotay khan',
    'sr4-p': 'Duto oshudh ekshathe khele drug interaction hote pare. Jemon Paracetamol er shathe Warfarin (blood thinner) ekshathe nile bipod. Oshudher shob tothho doctor ke janan.',
    'sr5-t': 'Antibiotic shompurno course shesh korun',
    'sr5-p': 'Bhalo laglei antibiotic bondho korbenna. Doctor jodi 7 diner course diyechen, shompurno 7 din khan. Adhek course e bacteria more na, boroncho resistant hoye jay.',
    'sr6-t': 'Pharmacist ke question korun',
    'sr6-p': 'Pharmacist shudhu oshudh bikri korenna — tara trained professional. Oshudher side effect, dose, ba interaction niye jekono proshno korun. Tara help korte prostut.',
    'dos-title': 'Ja korben', 'donts-title': 'Ja korbenna',
    'do1': 'Doctor er prescription mene cholun', 'do2': 'Pharmacist er poramorsho nin',
    'do3': 'Oshudher puro course shesh korun', 'do4': 'Expiry date dekhe oshudh kinun',
    'do5': 'Side effect hole doctor ke janan', 'do6': 'Oshudh thanda o shushko jaygay rakhun',
    'do7': 'Allergy thakle doctor ke age bolun',
    'dont1': 'Doctor chhara antibiotic shuru korbenna', 'dont2': 'Majhpothe oshudh bondho korbenna',
    'dont3': 'Onner oshudh nije nebenna', 'dont4': 'Expired oshudh khabenna',
    'dont5': 'Bathroom ba kitchen e oshudh rakhbenna', 'dont6': 'Ekshathe onek dhoroner oshudh nebenna',
    'dont7': 'Bacchader nagle oshudh rakhbenna',
    'gen-title': 'Generic vs Brand — ki difference?',
    'gen-desc': 'Eki oshudh bhinno name e bikri hoy. Generic naam ta holo mul chemical er naam — eta shob brand e eki kaj kore.',
    'gc1': 'Paracetamol (Generic)', 'gc1b': 'Napa, Ace, Renova, Tylenol, Panadol', 'gc1c': 'Eki oshudh, alada brand name',
    'gc2': 'Omeprazole (Generic)', 'gc2b': 'Omez, Losec, Prilosec, Seclo', 'gc2c': 'Shosta generic nileo eki kaj hoy',
    'gc3': 'Cetirizine (Generic)', 'gc3b': 'Alatrol, Cetrizin, Zyrtec, Allegra', 'gc3c': 'Pharmacist ke generic chaite paren',
    'fq-title': 'Shobcheye common questions', 'fq-desc': 'Manush je proshno gulo shobcheye beshi kore — shohoj bhashay uttor.',
    'fq1-q': '<span class="faq-badge badge-danger"><i class="fi fi-sr-triangle-warning"></i> Antibiotic</span>Bhalo laglei ki antibiotic bondho kora jabe?',
    'fq1-a': 'Na, ekdom i na. Doctor jodi 5 diner course diyechen, 3 dine i bhalo lagleo baki 2 din khan. Karon — 3 dine 90% bacteria more jay, kintu baki 10% shobcheye shoktishali. Eder mere na felle pore antibiotic kaj korbena (Antibiotic Resistance).',
    'fq2-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-capsule"></i> Painkiller</span>Betha beshi hole ki 2 ta Painkiller ekshathe khele beshi kaj hobe?',
    'fq2-a': 'Na! Eki dhoroner 2 ta painkiller (jemon 2 ta paracetamol ba paracetamol + ibuprofen) ekshathe khawa bipodjonok. Ete liver ba stomach er marattok khoti hote pare. Beshi bethay dose baranor age doctor er shathe kotha bolun.',
    'fq3-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-flower"></i> Birth Pill</span>Birth control pill ekti miss hole ki korbo?',
    'fq3-a': 'Jodi mone porle 24 ghontar moddhe ekti pill khan. Jodi 24 ghontar beshi hoye jay, tahole shei pill bad din ebong porer din theke swabavik somoy e khan. Kintu ei somoy otirrikto shotorko thakun. 2 ta pill miss hole tatkhonik doctor er poramorsho nin.',
    'fq4-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-alarm-clock"></i> Expiry</span>Emergency te expired oshudh khawa ki safe?',
    'fq4-a': 'Beshirbhag solid tablet kichu ta kom effective hoy — shathe shathe bishakto hoy na. Kintu liquid antibiotic, eye drop, insulin o injection expired hole bipodjonok hote pare. Jotofa shombhob fresh oshudh bybohar korun ebong expired oshudh ghore na rekhe fele din.',
    'fq5-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-comment-alt"></i> Generic</span>Pharmacist bhinno brand dile ki eki kaj hobe?',
    'fq5-a': 'Ha, shadharonoto. Doctor Napa likhleo Pharmacist Ace ba Renova dile eki kaj hoy — karon shober mul chemical Paracetamol. Ei oshudh guloke Generic bole. Tobe kichu special oshudher khetre (jemon thyroid, seizure) brand bodlano uchit noy. Shondeho hole pharmacist ke jiggesh korun.',
    'fq6-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-moon"></i> Sleeping Pill</span>Ghumer oshudh ki safe?',
    'fq6-a': 'Sleeping pill short-term e doctor er prescription e safe. Kintu long-term e (2 shoptaher beshi) addictive hoye jay. Hothat bondho korle withdrawal hoy. Ghumer shomossar permanent solution er jonno lifestyle change korun o doctor er poramorsho nin.',
    'fq7-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-heart-rate"></i> Gastric</span>Gastric er oshudh ki protidin khawa thik?',
    'fq7-a': 'Na, protidin khawa thik noy. Proyojone shorbochcho 4-8 shoptaho khawa jay. Er beshi khele haad durbol howa, Vitamin B12 kome jawa ebong kidney problem hote pare. Lifestyle change korun — moshladar khabar koman, shomoy moto khan.',
    'fq8-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-head-side-cough"></i> Allergy</span>Allergy er oshudh khele ki gari chalano jabe?',
    'fq8-a': 'Purono antihistamine (jemon Phenergan, Avil, Chlorpheniramine) khele ghum ashe — gari chalano dangerous. Notun antihistamine (Cetirizine, Loratadine, Fexofenadine) comparatively kom ghumobhab dey. Tobe jekono allergy oshudh khawar pore nijer condition bujhe gari chalan.',
    'ab-tag': 'About', 'ab-title': 'Ei initiative er pichoner golpo',
    'founder-name': 'Habeba Hussain', 'founder-role': 'Pharmacy Student & Fellow',
    'ab-p1': 'Bangladesh er odhikangsh working class manush — garments worker, rickshaw puller, dokandar, grihokormi — oshudh shomporke shothik tothho janen na. Tara pray i pasher dokan theke nijei oshudh kine khan, doctor er kache jawar time o taka dutor i nei.',
    'ab-p2': 'Pharmacy te porte giye dekhlam, ei manush gulo shudhu ektu shothik information peleo onek bipod erate parten. Antibiotic resistance, overdose, expired medicine — ei problem gulo shudhu knowledge er obhabe i hochhe.',
    'ab-p3': 'Ei website ta toiri hoyeche shei manush guler jonno. Simple Bangla te, shorol bhashay — jate je keu bujhte paren. Local pharmacy te QR code poster thakbe — oshudh kinte giyei scan kore jante parben.',
    'fel-title': 'Fellowship Program — Round 2',
    'fel-desc': 'Ei project ta ekti Fellowship Program er part hishebe toiri hoyeche. Goal: Working class manusher moddhe oshudh awareness barano.',
    'mis-title': 'Amader mission',
    'mp1': 'Simple bhashay oshudher shothik information deowa',
    'mp2': 'Antibiotic misuse o resistance niye awareness',
    'mp3': 'QR code er maddhome pharmacy te directly info pouche deowa',
    'mp4': 'Expired medicine er danger theke manush ke protect kora',
    'mp5': 'Working class o kom educated manusher health protection',
    'cont-title': 'Jogajog korun',
    'cont-role': 'Pharmacy Student, Bangladesh',
    'disclaimer-text': 'Ei website ta shudhu awareness er jonno. Treatment er jonno shobshomoy qualified doctor er poramorsho nin.',
    'qr-cta-title': 'QR Code Poster',
    'qr-cta-desc': 'Local pharmacy te ei poster thakbe. Scan korle directly ei website e asha jabe.',
    'qr-btn': '<i class="fi fi-rr-smartphone"></i> QR Code dekhun',
    'qr-title': 'Pharmacy Poster QR Code',
    'qr-desc': 'Nicher QR Code ta scan korun ba print kore pharmacy te lagan.',
    'poster-head': '<i class="fi fi-rr-document" style="margin-right:6px;"></i> Poster Text',
    'poster-line1': '<i class="fi fi-rr-capsule" style="margin-right:4px;"></i> Oshudh kinchen?',
    'poster-line2': 'Shothikbhabe bybohar korun.<br>Ei QR code scan korun ebong free te janun.',
    'poster-cta': 'Oshudh Ki Boss? | Oshudh jani, health pai',
    'qr-caption': 'Ei QR Code scan korle directly ei website e asha jabe.',
    'dl-btn': '<i class="fi fi-rr-download"></i> QR Download korun',
    'print-btn': '<i class="fi fi-rr-print"></i> Print korun',
    'ft-desc': 'Bangladesh er working class manusher jonno oshudh awareness er ekti initiative. Simple bhashay, free of charge.',
    'fl1': 'Home', 'fl2': 'Oshudh', 'fl3': 'Meyad', 'fl4': 'Safety', 'fl5': 'FAQ',
    'fl6': 'About', 'fl7': 'QR Code',
    'ft-disclaimer': '<i class="fi fi-sr-triangle-warning"></i> Ei website shudhu awareness er jonno toiri. Treatment er jonno shobshomoy qualified doctor ba pharmacist er poramorsho nin.',
  },
  banglish: {
    'logo-text': 'Oshudh Ki Boss?',
    'logo-sub': 'Oshudh jani, health pai',
    'n-home': 'Home', 'n-med': 'Oshudh', 'n-exp': 'Meyad & Storage',
    'n-safe': 'Safety Tips', 'n-about': 'About',
    'mn-home': 'Home', 'mn-med': 'Oshudh',
    'mn-exp': 'Meyad & Storage', 'mn-safe': 'Safety Tips',
    'mn-about': 'About',
    'hero-tag': 'Bangladesh er working class manusher jonno',
    'hero-title-main': 'Oshudh Ki Boss?',
    'hero-sub-bn': 'Oshudh jani, health pai',
    'hero-sub-en': 'Know Your Medicine, Gain Health',
    'stat1': 'Doctor chhara oshudh', 'stat2': 'AMR-e death (2019)', 'stat3': 'Sleeping pill users',
    'cta-learn': '<i class="fi fi-rr-capsule"></i> <span>Oshudh shomporke janun</span>',
    'cta-tips': '<i class="fi fi-rr-shield-check"></i> <span>Safety Tips</span>',
    'hc1-title': 'Antibiotic Resistance barche!',
    'hc1-text': 'Bhul bhabe antibiotic use korle shorir e resistant bacteria toiri hoy. Result e future e oshudh kaj korena.',
    'hc2-title': 'Prescription chhara oshudh noy',
    'hc2-text': 'WHO bolche, Bangladesh e odhikangsh oshudh doctor er poramorsho chharai kena hoy. Eta otyonto dangerous.',
    'warn-text': '<strong>Janen ki?</strong> Bhul bhabe oshudh khele liver, kidney o shorir er important organ er khoti hote pare. Shocheton hon, shustho thakun.',
    's1': 'Antibiotic er full course shesh korun',
    's2': 'Expiry date dekhe oshudh kinun',
    's3': 'Doctor er prescription chhara sleeping pill noy',
    's4': 'Onner oshudh nije khabenna',
    's5': 'Bacchader nagler baire oshudh rakhun',
    's1b': 'Antibiotic er full course shesh korun',
    's2b': 'Expiry date dekhe oshudh kinun',
    's3b': 'Doctor er prescription chhara sleeping pill noy',
    's4b': 'Onner oshudh nije khabenna',
    's5b': 'Bacchader nagler baire oshudh rakhun',
    'mt-tag': 'Oshudh Info',
    'mt-title': 'Common oshudh er shothik use',
    'mt-desc': 'Protita oshudh er shothik info janun — keno khaben, kibhabe khaben, ebong kokhon shotorko hoben.',
    'fa': 'Shob oshudh', 'fb': 'Antibiotics', 'fc': 'Sleeping Pills',
    'fd': 'Gastric', 'fe': 'Painkillers', 'ff': 'Birth Control',
    'm1-title': 'Antibiotics',
    'm1-desc': 'Antibiotic holo emon oshudh ja bacteriar infection thik kore. Kintu onek e sordi-jore o antibiotic khan — eta bhul ebong dangerous. Virus e antibiotic kaj kore na.',
    'm1t1': 'Doctor er poramorsho chhara antibiotic khaben na',
    'm1t2': 'Full course shesh korun — majhe bondho korben na',
    'm1t3': 'Onner antibiotic nije use korben na',
    'm1t4': 'Khabarer shathe ba pore khele pet er problem kombe',
    'm1-stat': 'Bangladesh e 2019 e <strong>AMR er karone 26,200 jon</strong> mara gechen. (WHO / The Business Standard)',
    'm2-title': 'Sleeping Pills',
    'm2-desc': 'Ghumer problem e onek e ei oshudh use koren. Egulo benzodiazepine type — shudhu doctor er prescription e paowa uchit. Era addictive ebong long-term e memory te effect fele.',
    'm2t1': 'Kokhono nije theke start korben na — Prescription must',
    'm2t2': 'Gari chalaben na ba heavy kaj korben na',
    'm2t3': 'Alcohol er shathe never — very dangerous',
    'm2t4': 'Suddenly bondho na kore doctor er advice e slowly koman',
    'm2-stat': 'Bangladesh e pray <strong>3 lakh manush</strong> sleeping pill ba sedative use koren. (The Daily Star)',
    'm3-title': 'Gastric Medicine',
    'm3-desc': 'Bangladesh e gastric er oshudh shobcheye beshi khawa hoy. Ei PPI oshudh long-term e na khawai better. Dorkar hole doctor dekhan.',
    'm3t1': 'Khabar age (khali pete) 20-30 min age khan',
    'm3t2': 'Long-term e (8 week er beshi) doctor chhara noy',
    'm3t3': 'Spicy o fried food koman',
    'm3t4': 'Rate showar age khabenna',
    'm3-stat': 'Long-term use e <strong>Vitamin B12, Magnesium o Calcium</strong> absorption e problem hoy. (Banglajol Medical Journal)',
    'm4-title': 'Painkillers',
    'm4-desc': 'Painkiller shobcheye beshi used oshudh. Paracetamol normally safe, kintu high dose e liver damage kore. Ibuprofen pet kharap korte pare. 2 ta painkiller together khawa dangerous.',
    'm4t1': 'Adults er jonno Paracetamol max 500mg x 4 times daily',
    'm4t2': 'Ibuprofen food er shathe khan — empty stomach e noy',
    'm4t3': '2 ta painkiller together khaben na',
    'm4t4': '3 diner beshi doctor chhara noy',
    'm4-stat': 'Paracetamol overdose world er onnotomo main <strong>acute liver failure er cause</strong>. Right dose follow korun.',
    'm5-title': 'Birth Control Pills',
    'm5-desc': 'Birth control pill properly protidin same time e khete hoy. Ekta pill miss hole effectiveness kome jay. Emergency pill regularly use kora uchit na.',
    'm5t1': 'Protidin same time e khan — breakfast er por bhalo',
    'm5t2': 'Ek ta pill miss hole porerdin 2 ta khan ebong extra careful thakun',
    'm5t3': 'Breastfeeding ma ra bhinno type er pill use korun',
    'm5t4': 'Start korar age doctor ba pharmacist er advice nin',
    'm5-stat': 'Properly use korle OCP <strong>99%+ effective</strong>. But wrong use e effectiveness 91% e neme ashe.',
    'm6-title': 'Antihistamine / Allergy Medicine',
    'm6-desc': 'Allergy, sneeze, itching, rash er jonno ei oshudh use hoy. Old antihistamine (Chlorpheniramine, Phenergan) ghum bhab create kore. Onek e eta na jene gari chalan — dangerous!',
    'm6t1': 'Old antihistamine (Phenergan, Avil) rate nin',
    'm6t2': 'New antihistamine (Cetirizine, Loratadine) kom drowsy kore',
    'm6t3': 'Khawar por gari chalaben na',
    'm6t4': 'Bacchader dose adults er theke alada — careful',
    'm6-stat': 'Bangladesh e onek e <strong>Phenergan ba Avil</strong> cough medicine hishebe khan — kintu eta antihistamine and sedative.',
    'et-tag': 'Meyad & Storage', 'et-title': 'Oshudher expiry o proper storage',
    'et-desc': 'Expired oshudh khele kono benefit nei, ulta harm hote pare. Properly store na korle oshudh age i noshto hoy.',
    'eh-title': 'EXP: 07/2027 — Er mane ki?',
    'eh-text': 'Protita oshudher packet e EXP ba Expiry Date lekha thake. Ei date mane holo — ei month er last day porjonto oshudh ta usable. Tarpor theke oshudher chemical change hote pare ebong effectiveness kome.',
    'eh-text2': 'Bangladesh er hot o humid weather e oshudh aro fast noshto hoy. Tai proper place e rakha important.',
    'exp-meaning': 'July 2027 er por use korbenna',
    'before-exp': 'Expiry er moddhe', 'after-exp': 'Expired',
    'exp-cards-title': 'Expiry related important info',
    'ec1-t': 'Kothay dekhben?', 'ec1-p': 'Oshudher strip er pichone, box er niche ba bottle er label e normally EXP ba Exp. Date lekha thake. "MFG" mane making date, "EXP" mane expiry date.',
    'ec2-t': 'Expired oshudh khele ki hoy?', 'ec2-p': 'Kichu oshudh just kom effective hoy, abar kichu toxic hoye jay. Especially eye drops, liquid antibiotics o insulin expired hole dangerous. Risk newa uchit na.',
    'ec3-t': 'Purono oshudh throw korbenna kibhabe?', 'ec3-p': 'Pani te felbenna — environment pollute hoy. Toilet e flush korbenna. Ekta sealed bag e bhore dustbin e felun, or kacher pharmacy te joma din.',
    'store-title': 'Oshudh kibhabe store korben',
    'sc1-t': 'Heat theke bachan', 'sc1-p': 'Most oshudh room temperature (15-25°C) e rakhun. Bangladesh er gorome medicine cabinet thanda jaygay rakhun. Direct sunlight theke dure rakhun.',
    'sc2-t': 'Humidity avoid korun', 'sc2-p': 'Bathroom e oshudh rakhbenna — steam oshudh noshto kore. Original packaging e rakhun ebong tight kore bondho rakhun.',
    'sc3-t': 'Bacchader reach er baire', 'sc3-p': 'Bacchara colorful tablet dekhle candy mone kore kheye felte pare. Always locked cabinet e ba high place e rakhun.',
    'sc4-t': 'Fridge e rakhar oshudh', 'sc4-p': 'Insulin, kichu eye drops o liquid antibiotic fridge e rakhte hoy. Freeze korbenna. "Store in Cool Place" lekha oshudh gulo fridge er door e rakhun.',
    'st-tag': 'Safety', 'st-title': 'Oshudh use er golden rules',
    'st-desc': 'Ei simple rules gulo follow korle most medicine-related accidents avoid kora possible.',
    'sr1-t': 'Doctor er advice chhara oshudh khaben na',
    'sr1-p': 'Protita manusher body different. Apnar neighbour er je oshudh kaj koreche, sheta apnar jonno dangerous hote pare. Especially antibiotic, steroid o sleeping pill er case e prescription must.',
    'sr2-t': 'Onner oshudh use korben na',
    'sr2-p': 'Same symptoms thakleo reason different hote pare. Onner oshudh nile apnar problem barte pare ebong correct diagnosis late hobe.',
    'sr3-t': 'Label fully porun',
    'sr3-p': 'Dose, kotbar khaben, food er age na pore — ei info gulo label e thake. Porte na parle pharmacist ke ask korun.',
    'sr4-t': 'Multiple oshudh carefully khan',
    'sr4-p': '2 ta oshudh together khele drug interaction hote pare. Example: Paracetamol er shathe Warfarin (blood thinner) together nile danger. Shob medicine er info doctor ke janan.',
    'sr5-t': 'Antibiotic full course complete korun',
    'sr5-p': 'Better feel korlei antibiotic stop korbenna. Doctor jodi 7 day course diyechen, full 7 din khan. Half course e bacteria more na, instead resistant hoye jay.',
    'sr6-t': 'Pharmacist ke question korun',
    'sr6-p': 'Pharmacist shudhu oshudh sell kore na — tara trained professional. Side effect, dose, ba interaction niye any question korun. Tara help korte ready.',
    'dos-title': 'Ja korben', 'donts-title': 'Ja korbenna',
    'do1': 'Doctor er prescription follow korun', 'do2': 'Pharmacist er advice nin',
    'do3': 'Oshudher full course complete korun', 'do4': 'Expiry date check kore oshudh kinun',
    'do5': 'Side effect hole doctor ke janan', 'do6': 'Oshudh cool o dry place e rakhun',
    'do7': 'Allergy thakle doctor ke age bolun',
    'dont1': 'Doctor chhara antibiotic start korbenna', 'dont2': 'Middle te oshudh stop korbenna',
    'dont3': 'Onner oshudh nije nebenna', 'dont4': 'Expired oshudh khabenna',
    'dont5': 'Bathroom ba kitchen e oshudh rakhbenna', 'dont6': 'Together onek type er oshudh nebenna',
    'dont7': 'Bacchader reach e oshudh rakhbenna',
    'gen-title': 'Generic vs Brand — ki difference?',
    'gen-desc': 'Same oshudh different name e sell hoy. Generic name ta holo main chemical er name — eta shob brand e same kaj kore.',
    'gc1': 'Paracetamol (Generic)', 'gc1b': 'Napa, Ace, Renova, Tylenol, Panadol', 'gc1c': 'Same oshudh, different brand name',
    'gc2': 'Omeprazole (Generic)', 'gc2b': 'Omez, Losec, Prilosec, Seclo', 'gc2c': 'Cheap generic teo same kaj hoy',
    'gc3': 'Cetirizine (Generic)', 'gc3b': 'Alatrol, Cetrizin, Zyrtec, Allegra', 'gc3c': 'Pharmacist ke generic chaite paren',
    'fq-title': 'Most common questions', 'fq-desc': 'Manush je proshno gulo shobcheye beshi kore — easy answer.',
    'fq1-q': '<span class="faq-badge badge-danger"><i class="fi fi-sr-triangle-warning"></i> Antibiotic</span>Better feel korle ki antibiotic bondho kora jabe?',
    'fq1-a': 'Na, absolutely na. Doctor jodi 5 diner course diyechen, 3 dine better feel korlew baki 2 din khan. Karon — 3 dine 90% bacteria more, kintu baki 10% shobcheye strong. Tader na marle pore antibiotic kaje ashe na (Antibiotic Resistance).',
    'fq2-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-capsule"></i> Painkiller</span>Betha beshi hole 2 ta Painkiller together khele beshi kaj hobe?',
    'fq2-a': 'Na! Same type er 2 ta painkiller (jemon 2 ta paracetamol ba paracetamol + ibuprofen) together khawa dangerous. Ete liver ba stomach er deadly damage hote pare. Severe pain e dose baranor age doctor er shathe kotha bolun.',
    'fq3-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-flower"></i> Birth Pill</span>Birth control pill ekta miss hole ki korbo?',
    'fq3-a': '24 hour er moddhe mone porle ekta pill khan. 24 hour er beshi hoye gele, shei pill skip korun ebong next din theke normal time e khan. But ei time extra careful thakun. 2 ta pill miss hole immediately doctor er advice nin.',
    'fq4-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-alarm-clock"></i> Expiry</span>Emergency te expired oshudh khawa ki safe?',
    'fq4-a': 'Most solid tablet kichu ta kom effective hoy — immediately toxic hoy na. But liquid antibiotic, eye drop, insulin o injection expired hole dangerous hote pare. Jotota possible fresh oshudh use korun ebong expired oshudh ghor e na rekhe fele din.',
    'fq5-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-comment-alt"></i> Generic</span>Pharmacist different brand dile ki same kaj hobe?',
    'fq5-a': 'Ha, usually. Doctor Napa likhleo Pharmacist Ace ba Renova dile same kaj hoy — karon shober main chemical Paracetamol. Ei gulo ke Generic bole. But kichu special medicine er case e (jemon thyroid, seizure) brand change kora uchit na. Doubt hole pharmacist ke ask korun.',
    'fq6-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-moon"></i> Sleeping Pill</span>Sleeping pill ki safe?',
    'fq6-a': 'Sleeping pill short-term e doctor er prescription e safe. But long-term e (2 week er beshi) addictive hoye jay. Suddenly stop korle withdrawal hoy. Ghumer problem er permanent fix er jonno lifestyle change korun o doctor er advice nin.',
    'fq7-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-heart-rate"></i> Gastric</span>Gastric medicine ki daily khawa okay?',
    'fq7-a': 'Na, daily khawa okay na. Max 4-8 week dorkar hole khawa jay. Er beshi khele weak bones, low Vitamin B12, kidney problem hote pare. Lifestyle change korun — spicy food koman, time moto khan.',
    'fq8-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-head-side-cough"></i> Allergy</span>Allergy medicine khele ki drive kora jabe?',
    'fq8-a': 'Old antihistamine (jemon Phenergan, Avil, Chlorpheniramine) khele ghum ashe — driving dangerous. New antihistamine (Cetirizine, Loratadine, Fexofenadine) comparatively kom drowsy kore. But any allergy medicine khawar por own condition bujhe drive korun.',
    'ab-tag': 'About', 'ab-title': 'Ei initiative er pichoner golpo',
    'founder-name': 'Habeba Hussain', 'founder-role': 'Pharmacy Student & Fellow',
    'ab-p1': 'Bangladesh er most working class manush — garments worker, rickshaw puller, dokandar, domestic worker — oshudh shomporke right info janenna. Tara often nearby dokan theke nijei oshudh kine khan, doctor er kache jawar time o taka dutor i nei.',
    'ab-p2': 'Pharmacy te study korte giye dekhlam, ei manush gulo just ektu right information peleo onek danger avoid korte parten. Antibiotic resistance, overdose, expired medicine — ei problem gulo just knowledge er lack e hochhe.',
    'ab-p3': 'Ei website ta banano hoyeche oi manush guler jonno. Simple Bangla te, easy bhashay — jate jekeu bujhte pare. Local pharmacy te QR code poster thakbe — oshudh kinte giyei scan kore jante parben.',
    'fel-title': 'Fellowship Program — Round 2',
    'fel-desc': 'Ei project ta ekta Fellowship Program er part hishebe banano hoyeche. Goal: Working class manusher moddhe medicine awareness barano.',
    'mis-title': 'Amader mission',
    'mp1': 'Simple language e oshudher right info provide kora',
    'mp2': 'Antibiotic misuse o resistance niye awareness',
    'mp3': 'QR code er through pharmacy te directly info pouche deowa',
    'mp4': 'Expired medicine er danger theke manush ke protect kora',
    'mp5': 'Working class o less educated manusher health safety',
    'cont-title': 'Contact korun',
    'cont-role': 'Pharmacy Student, Bangladesh',
    'disclaimer-text': 'Ei website shudhu awareness er jonno. Treatment er jonno always qualified doctor er advice nin.',
    'qr-cta-title': 'QR Code Poster',
    'qr-cta-desc': 'Local pharmacy te ei poster thakbe. Scan korle directly ei website e asbe.',
    'qr-btn': '<i class="fi fi-rr-smartphone"></i> QR Code dekhun',
    'qr-title': 'Pharmacy Poster QR Code',
    'qr-desc': 'Nicher QR Code ta scan korun or print kore pharmacy te lagan.',
    'poster-head': '<i class="fi fi-rr-document" style="margin-right:6px;"></i> Poster Text',
    'poster-line1': '<i class="fi fi-rr-capsule" style="margin-right:4px;"></i> Oshudh kinchen?',
    'poster-line2': 'Properly use korun.<br>Ei QR code scan korun ebong free te janun.',
    'poster-cta': 'Oshudh Ki Boss? | Oshudh jani, health pai',
    'qr-caption': 'Ei QR Code scan korle directly ei website e asha jabe.',
    'dl-btn': '<i class="fi fi-rr-download"></i> QR Download korun',
    'print-btn': '<i class="fi fi-rr-print"></i> Print korun',
    'ft-desc': 'Bangladesh er working class manusher jonno oshudh awareness initiative. Simple bhashay, free te.',
    'fl1': 'Home', 'fl2': 'Oshudh', 'fl3': 'Meyad', 'fl4': 'Safety', 'fl5': 'FAQ',
    'fl6': 'About', 'fl7': 'QR Code',
    'ft-disclaimer': '<i class="fi fi-sr-triangle-warning"></i> Ei website shudhu awareness er jonno. Treatment er jonno always qualified doctor ba pharmacist er advice nin.',
  }
};

let currentLang = localStorage.getItem('oshudh-lang') || 'bn';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('oshudh-lang', lang);
  
  document.getElementById('btn-bn').classList.toggle('active', lang === 'bn');
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-both').classList.toggle('active', lang === 'both');

  if (lang === 'en') {
    document.body.classList.remove('lang-bn');
    applyTranslations('en');
  } else if (lang === 'both') {
    // Banglish mode — Roman script Bangla mixed with English
    document.body.classList.remove('lang-bn');
    applyTranslations('banglish');
  } else {
    document.body.classList.add('lang-bn');
    applyTranslations('bn');
  }

  // Preserve active nav highlighting
  preserveNavHighlight();
}

function applyTranslations(lang) {
  const t = translations[lang];
  if (!t) return;
  for (const [id, text] of Object.entries(t)) {
    const el = document.getElementById(id);
    if (el) el.innerHTML = text;
  }
}

function preserveNavHighlight() {
  const activeSection = document.querySelector('section.active');
  if (activeSection) {
    const id = activeSection.id;
    document.querySelectorAll('.nav-links a').forEach(a => a.classList.remove('active'));
    const navMap = { home:'nav-home', medicines:'nav-medicines', expiry:'nav-expiry', safety:'nav-safety', faq:'nav-faq', about:'nav-about', 'qr-page':'nav-about' };
    const navEl = document.getElementById(navMap[id]);
    if (navEl) navEl.classList.add('active');
  }
}

// Init
document.addEventListener('DOMContentLoaded', () => {
  // Apply saved language
  const savedLang = localStorage.getItem('oshudh-lang');
  if (savedLang && savedLang !== 'bn') {
    setLang(savedLang);
  }

  // Close mobile menu on outside click
  document.addEventListener('click', (e) => {
    const menu = document.getElementById('mobileMenu');
    const ham = document.getElementById('hamburger');
    if (menu.classList.contains('open') && !menu.contains(e.target) && !ham.contains(e.target)) {
      menu.classList.remove('open');
    }
  });
});
</script>"""

content = content[0:js_start] + banglish_js + content[js_end:]

# ══════════════════════════════════════════════════════════════════════
# 3. Update the "Both" button label to "Banglish"
# ══════════════════════════════════════════════════════════════════════
content = content.replace(
    '<i class="fi fi-rr-globe" style="font-size:14px;"></i> <span>Both</span>',
    '<i class="fi fi-rr-globe" style="font-size:14px;"></i> <span>Banglish</span>'
)

# ══════════════════════════════════════════════════════════════════════
# WRITE
# ══════════════════════════════════════════════════════════════════════
with open(r'f:\E\Downloads\YUMNA\oshudh-ki-boss.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done! Banglish mode applied.")
print(f"File size: {len(content)} chars")
