import re

with open(r'f:\E\Downloads\YUMNA\oshudh-ki-boss.html', 'r', encoding='utf-8') as f:
    content = f.read()

# ══════════════════════════════════════════════════════════════════════
# FIX: Replace the entire bn translation object with proper Bengali
# ══════════════════════════════════════════════════════════════════════

old_bn_block = """  bn: {
    'logo-text': 'ওষুধটা কী বস?',
    'logo-sub': 'Know Your Medicine',
    'n-home': 'হোম', 'n-med': 'ওষুধ সমূহ', 'n-exp': 'মেয়াদ ও সংরক্ষণ',
    'n-safe': 'নিরাপত্তা টিপস', 'n-about': 'আমাদের সম্পর্কে',
    'mn-home': 'হোম', 'mn-med': 'ওষুধ সমূহ',
    'mn-exp': 'মেয়াদ ও সংরক্ষণ', 'mn-safe': 'নিরাপত্তা টিপস',
    'mn-about': 'আমাদের সম্পর্কে',
    'hero-tag': 'বাংলাদেশের কর্মজীবী মানুষের জন্য',
    'hero-title-main': 'ওষুধটা কী বস?',
    'hero-sub-bn': 'ওষুধ জানি, স্বাস্থ্য পাই',
    'hero-sub-en': 'Know Your Medicine, Gain Health',
    'stat1': 'ডাক্তার ছাড়া ওষুধ', 'stat2': 'AMR-এ মৃত্যু (২০১৯)', 'stat3': 'ঘুমের ওষুধ ব্যবহারকারী',
    'cta-learn': '<i class="fi fi-rr-capsule"></i> <span>ওষুধ সম্পর্কে জানুন</span>',
    'cta-tips': '<i class="fi fi-rr-shield-check"></i> <span>নিরাপত্তা টিপস</span>',
    'hc1-title': 'Antibiotic Resistance বাড়ছে!',
    'hc1-text': 'ভুলভাবে antibiotic ব্যবহারে শরীরে resistant bacteria তৈরি হয়। ফলে ভবিষ্যতে ওষুধ কাজ করে না।',
    'hc2-title': 'Prescription ছাড়া ওষুধ নয়',
    'hc2-text': 'WHO বলছে, বাংলাদেশে অধিকাংশ ওষুধ doctor এর পরামর্শ ছাড়াই কেনা হয়। এটি অত্যন্ত বিপজ্জনক।',
    'warn-text': '<strong>জানেন কি?</strong> ভুলভাবে ওষুধ খেলে liver, kidney ও শরীরের গুরুত্বপূর্ণ অঙ্গের ক্ষতি হতে পারে। সচেতন হন, সুস্থ থাকুন।',
    's1': 'Antibiotic সম্পূর্ণ course শেষ করুন',
    's2': 'Expiry date দেখে ওষুধ কিনুন',
    's3': 'Doctor এর prescription ছাড়া ঘুমের ওষুধ নয়',
    's4': 'অন্যের ওষুধ নিজে খাবেন না',
    's5': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    's1b': 'Antibiotic সম্পূর্ণ course শেষ করুন',
    's2b': 'Expiry date দেখে ওষুধ কিনুন',
    's3b': 'Doctor এর prescription ছাড়া ঘুমের ওষুধ নয়',
    's4b': 'অন্যের ওষুধ নিজে খাবেন না',
    's5b': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    'mt-tag': 'ওষুধ তথ্য',
    'mt-title': 'সাধারণ ওষুধের সঠিক ব্যবহার',
    'mt-desc': 'প্রতিটি ওষুধ সম্পর্কে সঠিক তথ্য জানুন — কী কারণে খাবেন, কীভাবে খাবেন, এবং কখন সতর্ক হবেন।',
    'fa': 'সব ওষুধ', 'fb': 'Antibiotics', 'fc': 'ঘুমের ওষুধ',
    'fd': 'গ্যাস্ট্রিক', 'fe': 'Painkillers', 'ff': 'Birth Control',
    'm1-title': 'অ্যান্টিবায়োটিক',
    'm1-desc': 'Antibiotic holo emon oshudh ja bacteriar songkromon dur kore. Kintu onek e sordi-jore o antibiotic khan — eta bhul ebong bipodjonok. Virus-e antibiotic kaj kore na.',
    'm1t1': 'Doctor er poramorsho chhara antibiotic khabenna',
    'm1t2': 'Shompurno course shesh korun — majhpothe bondho korbenna',
    'm1t3': 'Onner antibiotic nije bybohar korbenna',
    'm1t4': 'Khabarer shathe ba pore khele peter shomossa kome',
    'm1-stat': 'বাংলাদেশে ২০১৯ সালে <strong>AMR-এর কারণে ২৬,২০০ জন</strong> মারা গেছেন। (WHO / The Business Standard)',
    'm2-title': 'ঘুমের ওষুধ',
    'm2-desc': 'Ghumer shomossay onek e ei oshudh bybohar koren. Egulo benzodiazepine shrenir — shudhumatro doctor er prescription e paowa uchit. Era addictive ebong dirghomeyade smritishokti te probhab fele.',
    'm2t1': 'Kokhono nije theke shuru korbenna — Prescription abosshok',
    'm2t2': 'Gari chalabenna ba bhari kaj korbenna',
    'm2t3': 'Alcohol er shathe ekdom noy — marattok bipod',
    'm2t4': 'Hothat bondho na kore doctor er poramorshe dhire dhire koman',
    'm2-stat': 'বাংলাদেশে প্রায় <strong>৩ লাখ মানুষ</strong> ঘুমের ওষুধ বা sedative ব্যবহার করেন। (The Daily Star)',
    'm3-title': 'গ্যাস্ট্রিকের ওষুধ',
    'm3-desc': 'Bangladesh e gastric er oshudh shobcheye beshi khawa hoy. Ei PPI (Proton Pump Inhibitor) oshudh dirghomeyade na khawai bhalo. Proyojone doctor dekhan.',
    'm3t1': 'Khabar age (khali pete) 20-30 minute age khan',
    'm3t2': 'Dirghomeyade (8 shoptaher beshi) doctor chhara noy',
    'm3t3': 'Moshladar o bhaja khabar koman',
    'm3t4': 'Rate showar age khabenna',
    'm3-stat': 'দীর্ঘমেয়াদী ব্যবহারে <strong>Vitamin B12, Magnesium ও Calcium</strong> শোষণে সমস্যা হয়। (Banglajol Medical Journal)',
    'm4-title': 'ব্যথার ওষুধ',
    'm4-desc': 'Painkiller shobcheye beshi bybohorito oshudh. Paracetamol shadharonoto nirapod, kintu beshi dose-e liver khoti kore. Ibuprofen pet kharap korte pare. Duto painkiller ekshathe khawa bipodjonok.',
    'm4t1': 'Praptoboyosker jonno Paracetamol shorbochcho 500mg x 4 bar dine',
    'm4t2': 'Ibuprofen khabarer shathe khan — khali pete noy',
    'm4t3': 'Duto painkiller ekshathe khabenna',
    'm4t4': '3 diner beshi doctor chhara noy',
    'm4-stat': 'Paracetamol overdose bisshwer onnotomo prodhan <strong>acute liver failure-er karon</strong>. Shothik dose mene cholun.',
    'm5-title': 'Birth Control Pill',
    'm5-desc': 'Birth control pill shothikbhabe protidin eki shomoy e khete hoy. Ekti pill miss hole effectiveness kome jay. Emergency pill niyomito bybohar kora uchit noy.',
    'm5t1': 'Protidin eki shomoy e khan — sokaler nastar pore bhalo',
    'm5t2': 'Ekti pill bad porle porer din duto khan ebong otirrikto shotorko thakun',
    'm5t3': 'Breast milk khaowano mayera bhinno dhoroner pill bybohar korun',
    'm5t4': 'Shuru korar age doctor ba pharmacist er poramorsho nin',
    'm5-stat': 'Shothikbhabe bybohar korle OCP <strong>99%+ effective</strong>. Kintu bhul bybohar e effectiveness 91%-e neme ashe.',
    'm6-title': 'Antihistamine / Allergy oshudh',
    'm6-desc': 'Allergy, hachi, chulkani, rash er jonno ei oshudh bybohar hoy. Purono antihistamine (Chlorpheniramine, Phenergan) ghumobhab shrishti kore. Onek e eta na jene gari chalan — bipodjonok!',
    'm6t1': 'Purono antihistamine (Phenergan, Avil) rate nin',
    'm6t2': 'Notun antihistamine (Cetirizine, Loratadine) kom ghumobhab dey',
    'm6t3': 'Khawar por gari chalabenna',
    'm6t4': 'Bacchader dose boro manusher cheye alada — sabdhan',
    'm6-stat': 'Bangladesh e onek e <strong>Phenergan ba Avil</strong> kashir oshudh hishebe khan — kintu eta antihistamine ebong sedative.',
    'et-tag': 'Meyad & Storage', 'et-title': 'Oshudher meyad o shothik shongrokkhon',
    'et-desc': 'Expired oshudh khele kono upokar nei, boroncho khoti hote pare. Shothikbhabe shongrokkhon na korle oshudh age i noshto hoy.',
    'eh-title': 'EXP: 07/2027 — Er mane ki?',
    'eh-text': 'Protiti oshudher packet e EXP ba Expiry Date lekha thake. Ei tarikh mane holo — ei masher shesh din porjonto oshudh ti byboharjojjo. Tarpor theke oshudher chemical bodle jete pare ebong effectiveness kome jay.',
    'eh-text2': 'Bangladesh er gorom o ardro abohawaye oshudh aro druto noshto hoy. Tai shothik jaygay rakha joruri.',
    'exp-meaning': 'July 2027 er por bybohar korbenna',
    'before-exp': 'Meyader moddhe', 'after-exp': 'Expired',
    'exp-cards-title': 'Meyad shongkranto important tothho',
    'ec1-t': 'Kothay dekhben?', 'ec1-p': 'Oshudher strip er pichhone, box er niche ba bottle er label e shadharonoto EXP ba Exp. Date lekha thake. "MFG" mane manufacturing date, "EXP" mane expiry date.',
    'ec2-t': 'Expired oshudh khele ki hoy?', 'ec2-p': 'Kichu oshudh shudhu kom effective hoy, abar kichu toxic hoye jay. Bisheshoto eye drops, liquid antibiotics o insulin expired hole bipodjonok. Risk newa uchit noy.',
    'ec3-t': 'Purono oshudh felbenna kibhabe?', 'ec3-p': 'Pani te felbenna — poribesh dushito hoy. Toilet e flush korbenna. Ekti sealed bag e bhore dustbin e felun, othoba kacher pharmacy te joma din.',
    'store-title': 'Oshudh kibhabe store korben',
    'sc1-t': 'Temperature theke bachan', 'sc1-p': 'Beshirbhag oshudh room temperature (15-25°C)-e rakhun. Bangladesh er gorome oshudher cabinet thanda jaygay rakhun. Direct sunlight theke dure rakhun.',
    'sc2-t': 'Humidity eiye cholun', 'sc2-p': 'Bathroom e oshudh rakhbenna — bhap oshudh noshto kore. Original packaging e rakhun ebong tight kore bondho rakhun.',
    'sc3-t': 'Bacchader nagler baire', 'sc3-p': 'Bacchara rangin tablet dekhle candy mone kore kheye felte pare. Shobshomoy lock kora cabinet e ba unchu jaygay rakhun.',
    'sc4-t': 'Fridge e rakhar oshudh', 'sc4-p': 'Insulin, kichu eye drops o liquid antibiotic fridge e rakhte hoy. Freeze korbenna. Je shob oshudhe "Store in Cool Place" lekha shegulo fridge er dorojay rakhun.',
    'st-tag': 'Safety', 'st-title': 'Oshudh byoboharer golden rules',
    'st-desc': 'Ei simple niymgulo mene cholle odhikangsh oshudh-jonito durghotona erano shombhob.',
    'sr1-t': 'Doctor er poramorsho chhara oshudh khabenna',
    'sr1-p': 'Protiti manusher shorir alada. Apnar neighbour er je oshudh kaj koreche, sheta apnar jonno bipodjonok hote pare. Bisheshoto antibiotic, steroid o sleeping pill er khetre prescription abosshok.',
    'sr2-t': 'Onner oshudh bybohar korbenna',
    'sr2-p': 'Eki roger symptom thakleo karon bhinno hote pare. Onner oshudh nile apnar rog barte pare ebong shothik diagnosis derir hobe.',
    'sr3-t': 'Label shompurno porun',
    'sr3-p': 'Dose, kotbar khaben, khabarer age na pore — ei tothho gulo label e thake. Porte na parle pharmacist ke jiggesh korun.',
    'sr4-t': 'Ekshathe onek oshudh shotorkotay khan',
    'sr4-p': 'Duto oshudh ekshathe khele drug interaction hote pare. Jemon Paracetamol er shathe Warfarin (blood thinner) ekshathe nile bipod. Oshudher shob tothho doctor ke janan.',
    'sr5-t': 'Antibiotic shompurno course shesh korun',
    'sr5-p': 'Bhalo laglei antibiotic bondho korbenna. Doctor jodi 7 diner course diyechen, shompurno 7 din khan. Adhek course e bacteria more na, boroncho resistant hoye jay.',
    'sr6-t': 'Pharmacist ke question korun',
    'sr6-p': 'Pharmacist shudhu oshudh bikri korenna — tara trained professional. Oshudher side effect, dose, ba interaction niye jekono proshno korun. Tara help korte prostut.',
    'dos-title': 'Ja korben', 'donts-title': 'Ja korbenna',
    'do1': 'Doctor er prescription mene cholun', 'do2': 'Pharmacist er poramorsho nin',
    'do3': 'Oshudher puro course shesh korun', 'do4': 'Expiry date dekhe oshudh kinun',
    'do5': 'Side effect hole doctor ke janan', 'do6': 'Oshudh thanda o shushko jaygay rakhun',
    'do7': 'Allergy thakle doctor ke age bolun',
    'dont1': 'Doctor chhara antibiotic shuru korbenna', 'dont2': 'Majhpothe oshudh bondho korbenna',
    'dont3': 'Onner oshudh nije nebenna', 'dont4': 'Expired oshudh khabenna',
    'dont5': 'Bathroom ba kitchen e oshudh rakhbenna', 'dont6': 'Ekshathe onek dhoroner oshudh nebenna',
    'dont7': 'Bacchader nagle oshudh rakhbenna',
    'gen-title': 'Generic vs Brand — ki difference?',
    'gen-desc': 'Eki oshudh bhinno name e bikri hoy. Generic naam ta holo mul chemical er naam — eta shob brand e eki kaj kore.',
    'gc1': 'Paracetamol (Generic)', 'gc1b': 'Napa, Ace, Renova, Tylenol, Panadol', 'gc1c': 'Eki oshudh, alada brand name',
    'gc2': 'Omeprazole (Generic)', 'gc2b': 'Omez, Losec, Prilosec, Seclo', 'gc2c': 'Shosta generic nileo eki kaj hoy',
    'gc3': 'Cetirizine (Generic)', 'gc3b': 'Alatrol, Cetrizin, Zyrtec, Allegra', 'gc3c': 'Pharmacist ke generic chaite paren',
    'fq-title': 'Shobcheye common questions', 'fq-desc': 'Manush je proshno gulo shobcheye beshi kore — shohoj bhashay uttor.',
    'fq1-q': '<span class="faq-badge badge-danger"><i class="fi fi-sr-triangle-warning"></i> Antibiotic</span>Bhalo laglei ki antibiotic bondho kora jabe?',
    'fq1-a': 'Na, ekdom i na. Doctor jodi 5 diner course diyechen, 3 dine i bhalo lagleo baki 2 din khan. Karon — 3 dine 90% bacteria more jay, kintu baki 10% shobcheye shoktishali. Eder mere na felle pore antibiotic kaj korbena (Antibiotic Resistance).',
    'fq2-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-capsule"></i> Painkiller</span>Betha beshi hole ki 2 ta Painkiller ekshathe khele beshi kaj hobe?',
    'fq2-a': 'Na! Eki dhoroner 2 ta painkiller (jemon 2 ta paracetamol ba paracetamol + ibuprofen) ekshathe khawa bipodjonok. Ete liver ba stomach er marattok khoti hote pare. Beshi bethay dose baranor age doctor er shathe kotha bolun.',
    'fq3-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-flower"></i> Birth Pill</span>Birth control pill ekti miss hole ki korbo?',
    'fq3-a': 'Jodi mone porle 24 ghontar moddhe ekti pill khan. Jodi 24 ghontar beshi hoye jay, tahole shei pill bad din ebong porer din theke swabavik somoy e khan. Kintu ei somoy otirrikto shotorko thakun. 2 ta pill miss hole tatkhonik doctor er poramorsho nin.',
    'fq4-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-alarm-clock"></i> Expiry</span>Emergency te expired oshudh khawa ki safe?',
    'fq4-a': 'Beshirbhag solid tablet kichu ta kom effective hoy — shathe shathe bishakto hoy na. Kintu liquid antibiotic, eye drop, insulin o injection expired hole bipodjonok hote pare. Jotofa shombhob fresh oshudh bybohar korun ebong expired oshudh ghore na rekhe fele din.',
    'fq5-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-comment-alt"></i> Generic</span>Pharmacist bhinno brand dile ki eki kaj hobe?',
    'fq5-a': 'Ha, shadharonoto. Doctor Napa likhleo Pharmacist Ace ba Renova dile eki kaj hoy — karon shober mul chemical Paracetamol. Ei oshudh guloke Generic bole. Tobe kichu special oshudher khetre (jemon thyroid, seizure) brand bodlano uchit noy. Shondeho hole pharmacist ke jiggesh korun.',
    'fq6-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-moon"></i> Sleeping Pill</span>Ghumer oshudh ki safe?',
    'fq6-a': 'Sleeping pill short-term e doctor er prescription e safe. Kintu long-term e (2 shoptaher beshi) addictive hoye jay. Hothat bondho korle withdrawal hoy. Ghumer shomossar permanent solution er jonno lifestyle change korun o doctor er poramorsho nin.',
    'fq7-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-heart-rate"></i> Gastric</span>Gastric er oshudh ki protidin khawa thik?',
    'fq7-a': 'Na, protidin khawa thik noy. Proyojone shorbochcho 4-8 shoptaho khawa jay. Er beshi khele haad durbol howa, Vitamin B12 kome jawa ebong kidney problem hote pare. Lifestyle change korun — moshladar khabar koman, shomoy moto khan.',
    'fq8-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-head-side-cough"></i> Allergy</span>Allergy er oshudh khele ki gari chalano jabe?',
    'fq8-a': 'Purono antihistamine (jemon Phenergan, Avil, Chlorpheniramine) khele ghum ashe — gari chalano dangerous. Notun antihistamine (Cetirizine, Loratadine, Fexofenadine) comparatively kom ghumobhab dey. Tobe jekono allergy oshudh khawar pore nijer condition bujhe gari chalan.',
    'ab-tag': 'About', 'ab-title': 'Ei initiative er pichoner golpo',
    'founder-name': 'Habeba Hussain', 'founder-role': 'Pharmacy Student & Fellow',
    'ab-p1': 'Bangladesh er odhikangsh working class manush — garments worker, rickshaw puller, dokandar, grihokormi — oshudh shomporke shothik tothho janen na. Tara pray i pasher dokan theke nijei oshudh kine khan, doctor er kache jawar time o taka dutor i nei.',
    'ab-p2': 'Pharmacy te porte giye dekhlam, ei manush gulo shudhu ektu shothik information peleo onek bipod erate parten. Antibiotic resistance, overdose, expired medicine — ei problem gulo shudhu knowledge er obhabe i hochhe.',
    'ab-p3': 'Ei website ta toiri hoyeche shei manush guler jonno. Simple Bangla te, shorol bhashay — jate je keu bujhte paren. Local pharmacy te QR code poster thakbe — oshudh kinte giyei scan kore jante parben.',
    'fel-title': 'Fellowship Program — Round 2',
    'fel-desc': 'Ei project ta ekti Fellowship Program er part hishebe toiri hoyeche. Goal: Working class manusher moddhe oshudh awareness barano.',
    'mis-title': 'Amader mission',
    'mp1': 'Simple bhashay oshudher shothik information deowa',
    'mp2': 'Antibiotic misuse o resistance niye awareness',
    'mp3': 'QR code er maddhome pharmacy te directly info pouche deowa',
    'mp4': 'Expired medicine er danger theke manush ke protect kora',
    'mp5': 'Working class o kom educated manusher health protection',
    'cont-title': 'Jogajog korun',
    'cont-role': 'Pharmacy Student, Bangladesh',
    'disclaimer-text': 'Ei website ta shudhu awareness er jonno. Treatment er jonno shobshomoy qualified doctor er poramorsho nin.',
    'qr-cta-title': 'QR Code Poster',
    'qr-cta-desc': 'Local pharmacy te ei poster thakbe. Scan korle directly ei website e asha jabe.',
    'qr-btn': '<i class="fi fi-rr-smartphone"></i> QR Code dekhun',
    'qr-title': 'Pharmacy Poster QR Code',
    'qr-desc': 'Nicher QR Code ta scan korun ba print kore pharmacy te lagan.',
    'poster-head': '<i class="fi fi-rr-document" style="margin-right:6px;"></i> Poster Text',
    'poster-line1': '<i class="fi fi-rr-capsule" style="margin-right:4px;"></i> Oshudh kinchen?',
    'poster-line2': 'Shothikbhabe bybohar korun.<br>Ei QR code scan korun ebong free te janun.',
    'poster-cta': 'Oshudh Ki Boss? | Oshudh jani, health pai',
    'qr-caption': 'Ei QR Code scan korle directly ei website e asha jabe.',
    'dl-btn': '<i class="fi fi-rr-download"></i> QR Download korun',
    'print-btn': '<i class="fi fi-rr-print"></i> Print korun',
    'ft-desc': 'Bangladesh er working class manusher jonno oshudh awareness er ekti initiative. Simple bhashay, free of charge.',
    'fl1': 'Home', 'fl2': 'Oshudh', 'fl3': 'Meyad', 'fl4': 'Safety', 'fl5': 'FAQ',
    'fl6': 'About', 'fl7': 'QR Code',
    'ft-disclaimer': '<i class="fi fi-sr-triangle-warning"></i> Ei website shudhu awareness er jonno toiri. Treatment er jonno shobshomoy qualified doctor ba pharmacist er poramorsho nin.',
  },"""

new_bn_block = """  bn: {
    'logo-text': 'ওষুধটা কী বস?',
    'logo-sub': 'ওষুধ জানি, স্বাস্থ্য পাই',
    'n-home': 'হোম', 'n-med': 'ওষুধ সমূহ', 'n-exp': 'মেয়াদ ও সংরক্ষণ',
    'n-safe': 'নিরাপত্তা টিপস', 'n-about': 'আমাদের সম্পর্কে',
    'mn-home': 'হোম', 'mn-med': 'ওষুধ সমূহ',
    'mn-exp': 'মেয়াদ ও সংরক্ষণ', 'mn-safe': 'নিরাপত্তা টিপস',
    'mn-about': 'আমাদের সম্পর্কে',
    'hero-tag': 'বাংলাদেশের কর্মজীবী মানুষের জন্য',
    'hero-title-main': 'ওষুধটা কী বস?',
    'hero-sub-bn': 'ওষুধ জানি, স্বাস্থ্য পাই',
    'hero-sub-en': 'Know Your Medicine, Gain Health',
    'stat1': 'ডাক্তার ছাড়া ওষুধ', 'stat2': 'AMR-এ মৃত্যু (২০১৯)', 'stat3': 'ঘুমের ওষুধ ব্যবহারকারী',
    'cta-learn': '<i class="fi fi-rr-capsule"></i> <span>ওষুধ সম্পর্কে জানুন</span>',
    'cta-tips': '<i class="fi fi-rr-shield-check"></i> <span>নিরাপত্তা টিপস</span>',
    'hc1-title': 'Antibiotic Resistance বাড়ছে!',
    'hc1-text': 'ভুলভাবে antibiotic ব্যবহারে শরীরে resistant bacteria তৈরি হয়। ফলে ভবিষ্যতে ওষুধ কাজ করে না।',
    'hc2-title': 'Prescription ছাড়া ওষুধ নয়',
    'hc2-text': 'WHO বলছে, বাংলাদেশে অধিকাংশ ওষুধ ডাক্তারের পরামর্শ ছাড়াই কেনা হয়। এটি অত্যন্ত বিপজ্জনক।',
    'warn-text': '<strong>জানেন কি?</strong> ভুলভাবে ওষুধ খেলে লিভার, কিডনি ও শরীরের গুরুত্বপূর্ণ অঙ্গের ক্ষতি হতে পারে। সচেতন হন, সুস্থ থাকুন।',
    's1': 'Antibiotic-এর সম্পূর্ণ কোর্স শেষ করুন',
    's2': 'মেয়াদ দেখে ওষুধ কিনুন',
    's3': 'ডাক্তারের prescription ছাড়া ঘুমের ওষুধ নয়',
    's4': 'অন্যের ওষুধ নিজে খাবেন না',
    's5': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    's1b': 'Antibiotic-এর সম্পূর্ণ কোর্স শেষ করুন',
    's2b': 'মেয়াদ দেখে ওষুধ কিনুন',
    's3b': 'ডাক্তারের prescription ছাড়া ঘুমের ওষুধ নয়',
    's4b': 'অন্যের ওষুধ নিজে খাবেন না',
    's5b': 'শিশুদের নাগালের বাইরে ওষুধ রাখুন',
    'mt-tag': 'ওষুধ তথ্য',
    'mt-title': 'সাধারণ ওষুধের সঠিক ব্যবহার',
    'mt-desc': 'প্রতিটি ওষুধ সম্পর্কে সঠিক তথ্য জানুন — কী কারণে খাবেন, কীভাবে খাবেন, এবং কখন সতর্ক হবেন।',
    'fa': 'সব ওষুধ', 'fb': 'অ্যান্টিবায়োটিক', 'fc': 'ঘুমের ওষুধ',
    'fd': 'গ্যাস্ট্রিক', 'fe': 'ব্যথানাশক', 'ff': 'জন্মনিয়ন্ত্রণ',
    'm1-title': 'অ্যান্টিবায়োটিক',
    'm1-desc': 'Antibiotic হলো এমন ওষুধ যা ব্যাকটেরিয়ার সংক্রমণ দূর করে। কিন্তু অনেকে সর্দি-জ্বরেও antibiotic খান — এটা ভুল এবং বিপজ্জনক। ভাইরাসে antibiotic কাজ করে না।',
    'm1t1': 'ডাক্তারের পরামর্শ ছাড়া antibiotic খাবেন না',
    'm1t2': 'সম্পূর্ণ কোর্স শেষ করুন — মাঝপথে বন্ধ করবেন না',
    'm1t3': 'অন্যের antibiotic নিজে ব্যবহার করবেন না',
    'm1t4': 'খাবারের সাথে বা পরে খেলে পেটের সমস্যা কমে',
    'm1-stat': 'বাংলাদেশে ২০১৯ সালে <strong>AMR-এর কারণে ২৬,২০০ জন</strong> মারা গেছেন। (WHO / The Business Standard)',
    'm2-title': 'ঘুমের ওষুধ',
    'm2-desc': 'ঘুমের সমস্যায় অনেকে এই ওষুধ ব্যবহার করেন। এগুলো benzodiazepine শ্রেণীর — শুধুমাত্র ডাক্তারের prescription-এ পাওয়া উচিত। এরা আসক্তি তৈরি করে এবং দীর্ঘমেয়াদে স্মৃতিশক্তিতে প্রভাব ফেলে।',
    'm2t1': 'কখনো নিজে থেকে শুরু করবেন না — Prescription আবশ্যক',
    'm2t2': 'গাড়ি চালাবেন না বা ভারী কাজ করবেন না',
    'm2t3': 'অ্যালকোহলের সাথে একদম নয় — মারাত্মক বিপদ',
    'm2t4': 'হঠাৎ বন্ধ না করে ডাক্তারের পরামর্শে ধীরে ধীরে কমান',
    'm2-stat': 'বাংলাদেশে প্রায় <strong>৩ লাখ মানুষ</strong> ঘুমের ওষুধ বা sedative ব্যবহার করেন। (The Daily Star)',
    'm3-title': 'গ্যাস্ট্রিকের ওষুধ',
    'm3-desc': 'বাংলাদেশে গ্যাস্ট্রিকের ওষুধ সবচেয়ে বেশি খাওয়া হয়। এই PPI (Proton Pump Inhibitor) ওষুধ দীর্ঘমেয়াদে না খাওয়াই ভালো। প্রয়োজনে ডাক্তার দেখান।',
    'm3t1': 'খাবারের আগে (খালি পেটে) ২০-৩০ মিনিট আগে খান',
    'm3t2': 'দীর্ঘমেয়াদে (৮ সপ্তাহের বেশি) ডাক্তার ছাড়া নয়',
    'm3t3': 'মশলাদার ও ভাজা খাবার কমান',
    'm3t4': 'রাতে শোয়ার আগে খাবেন না',
    'm3-stat': 'দীর্ঘমেয়াদী ব্যবহারে <strong>Vitamin B12, Magnesium ও Calcium</strong> শোষণে সমস্যা হয়। (Banglajol Medical Journal)',
    'm4-title': 'ব্যথার ওষুধ',
    'm4-desc': 'Painkiller সবচেয়ে বেশি ব্যবহৃত ওষুধ। Paracetamol সাধারণত নিরাপদ, কিন্তু বেশি ডোজে লিভারের ক্ষতি করে। Ibuprofen পেট খারাপ করতে পারে। দুটো painkiller একসাথে খাওয়া বিপজ্জনক।',
    'm4t1': 'প্রাপ্তবয়স্কের জন্য Paracetamol সর্বোচ্চ ৫০০mg × ৪ বার দিনে',
    'm4t2': 'Ibuprofen খাবারের সাথে খান — খালি পেটে নয়',
    'm4t3': 'দুটো painkiller একসাথে খাবেন না',
    'm4t4': '৩ দিনের বেশি ডাক্তার ছাড়া নয়',
    'm4-stat': 'Paracetamol overdose বিশ্বের অন্যতম প্রধান <strong>acute liver failure-এর কারণ</strong>। সঠিক ডোজ মেনে চলুন।',
    'm5-title': 'জন্মনিয়ন্ত্রণ পিল',
    'm5-desc': 'জন্মনিয়ন্ত্রণ পিল সঠিকভাবে প্রতিদিন একই সময়ে খেতে হয়। একটি পিল মিস হলে কার্যকারিতা কমে যায়। Emergency pill নিয়মিত ব্যবহার করা উচিত নয়।',
    'm5t1': 'প্রতিদিন একই সময়ে খান — সকালের নাস্তার পরে ভালো',
    'm5t2': 'একটি পিল বাদ পড়লে পরের দিন দুটো খান এবং অতিরিক্ত সতর্ক থাকুন',
    'm5t3': 'বুকের দুধ খাওয়ানো মায়েরা ভিন্ন ধরনের পিল ব্যবহার করুন',
    'm5t4': 'শুরু করার আগে ডাক্তার বা pharmacist-এর পরামর্শ নিন',
    'm5-stat': 'সঠিকভাবে ব্যবহার করলে OCP <strong>৯৯%+ কার্যকর</strong>। কিন্তু ভুল ব্যবহারে কার্যকারিতা ৯১%-এ নেমে আসে।',
    'm6-title': 'Antihistamine / অ্যালার্জির ওষুধ',
    'm6-desc': 'অ্যালার্জি, হাঁচি, চুলকানি, র‍্যাশের জন্য এই ওষুধ ব্যবহার হয়। পুরানো antihistamine (Chlorpheniramine, Phenergan) ঘুমের ভাব সৃষ্টি করে। অনেকে এটা না জেনে গাড়ি চালান — বিপজ্জনক!',
    'm6t1': 'পুরানো antihistamine (Phenergan, Avil) রাতে নিন',
    'm6t2': 'নতুন antihistamine (Cetirizine, Loratadine) কম ঘুমের ভাব দেয়',
    'm6t3': 'খাওয়ার পর গাড়ি চালাবেন না',
    'm6t4': 'বাচ্চাদের ডোজ বড়দের চেয়ে আলাদা — সাবধান',
    'm6-stat': 'বাংলাদেশে অনেকে <strong>Phenergan বা Avil</strong> কাশির ওষুধ হিসেবে খান — কিন্তু এটা antihistamine এবং sedative।',
    'et-tag': 'মেয়াদ ও সংরক্ষণ', 'et-title': 'ওষুধের মেয়াদ ও সঠিক সংরক্ষণ',
    'et-desc': 'মেয়াদ উত্তীর্ণ ওষুধ খেলে কোনো উপকার নেই, বরং ক্ষতি হতে পারে। সঠিকভাবে সংরক্ষণ না করলে ওষুধ আগেই নষ্ট হয়।',
    'eh-title': 'EXP: 07/2027 — এর মানে কী?',
    'eh-text': 'প্রতিটি ওষুধের প্যাকেটে EXP বা Expiry Date লেখা থাকে। এই তারিখ মানে হলো — এই মাসের শেষ দিন পর্যন্ত ওষুধটি ব্যবহারযোগ্য। তারপর থেকে ওষুধের রাসায়নিক বদলে যেতে পারে এবং কার্যকারিতা কমে যায়।',
    'eh-text2': 'বাংলাদেশের গরম ও আর্দ্র আবহাওয়ায় ওষুধ আরো দ্রুত নষ্ট হয়। তাই সঠিক জায়গায় রাখা জরুরি।',
    'exp-meaning': 'জুলাই ২০২৭-এর পর ব্যবহার করবেন না',
    'before-exp': 'মেয়াদের মধ্যে', 'after-exp': 'মেয়াদ উত্তীর্ণ',
    'exp-cards-title': 'মেয়াদ সংক্রান্ত গুরুত্বপূর্ণ তথ্য',
    'ec1-t': 'কোথায় দেখবেন?', 'ec1-p': 'ওষুধের স্ট্রিপের পেছনে, বক্সের নিচে বা বোতলের লেবেলে সাধারণত EXP বা Exp. Date লেখা থাকে। "MFG" মানে উৎপাদন তারিখ, "EXP" মানে মেয়াদ শেষের তারিখ।',
    'ec2-t': 'মেয়াদ উত্তীর্ণ ওষুধ খেলে কী হয়?', 'ec2-p': 'কিছু ওষুধ শুধু কম কার্যকর হয়, আবার কিছু বিষাক্ত হয়ে যায়। বিশেষত eye drops, তরল antibiotics ও insulin মেয়াদ শেষ হলে বিপজ্জনক। ঝুঁকি নেওয়া উচিত নয়।',
    'ec3-t': 'পুরানো ওষুধ ফেলবেন কীভাবে?', 'ec3-p': 'পানিতে ফেলবেন না — পরিবেশ দূষিত হয়। টয়লেটে ফ্লাশ করবেন না। একটি সিলড ব্যাগে ভরে ডাস্টবিনে ফেলুন, অথবা কাছের ফার্মেসিতে জমা দিন।',
    'store-title': 'ওষুধ কীভাবে সংরক্ষণ করবেন',
    'sc1-t': 'তাপমাত্রা থেকে বাঁচান', 'sc1-p': 'বেশিরভাগ ওষুধ ঘরের তাপমাত্রায় (১৫-২৫°C) রাখুন। বাংলাদেশের গরমে ওষুধের ক্যাবিনেট ঠাণ্ডা জায়গায় রাখুন। সরাসরি রোদ থেকে দূরে রাখুন।',
    'sc2-t': 'আর্দ্রতা এড়িয়ে চলুন', 'sc2-p': 'বাথরুমে ওষুধ রাখবেন না — ভাপ ওষুধ নষ্ট করে। মূল প্যাকেজিং-এ রাখুন এবং শক্ত করে বন্ধ রাখুন।',
    'sc3-t': 'বাচ্চাদের নাগালের বাইরে', 'sc3-p': 'বাচ্চারা রঙিন ট্যাবলেট দেখলে ক্যান্ডি মনে করে খেয়ে ফেলতে পারে। সবসময় লক করা ক্যাবিনেটে বা উঁচু জায়গায় রাখুন।',
    'sc4-t': 'ফ্রিজে রাখার ওষুধ', 'sc4-p': 'Insulin, কিছু eye drops ও তরল antibiotic ফ্রিজে রাখতে হয়। ফ্রিজ করবেন না। যেসব ওষুধে "Store in Cool Place" লেখা সেগুলো ফ্রিজের দরজায় রাখুন।',
    'st-tag': 'নিরাপত্তা', 'st-title': 'ওষুধ ব্যবহারের সোনালী নিয়ম',
    'st-desc': 'এই সহজ নিয়মগুলো মেনে চললে অধিকাংশ ওষুধ-জনিত দুর্ঘটনা এড়ানো সম্ভব।',
    'sr1-t': 'ডাক্তারের পরামর্শ ছাড়া ওষুধ খাবেন না',
    'sr1-p': 'প্রতিটি মানুষের শরীর আলাদা। আপনার প্রতিবেশীর যে ওষুধ কাজ করেছে, সেটা আপনার জন্য বিপজ্জনক হতে পারে। বিশেষত antibiotic, steroid ও ঘুমের ওষুধের ক্ষেত্রে prescription আবশ্যক।',
    'sr2-t': 'অন্যের ওষুধ ব্যবহার করবেন না',
    'sr2-p': 'একই রোগের লক্ষণ থাকলেও কারণ ভিন্ন হতে পারে। অন্যের ওষুধ নিলে আপনার রোগ বাড়তে পারে এবং সঠিক রোগ নির্ণয় দেরি হবে।',
    'sr3-t': 'লেবেল সম্পূর্ণ পড়ুন',
    'sr3-p': 'ডোজ, কতবার খাবেন, খাবারের আগে না পরে — এই তথ্যগুলো লেবেলে থাকে। পড়তে না পারলে pharmacist-কে জিজ্ঞেস করুন।',
    'sr4-t': 'একসাথে অনেক ওষুধ সতর্কতায় খান',
    'sr4-p': 'দুটো ওষুধ একসাথে খেলে drug interaction হতে পারে। যেমন Paracetamol-এর সাথে Warfarin (blood thinner) একসাথে নিলে বিপদ। ওষুধের সব তথ্য ডাক্তারকে জানান।',
    'sr5-t': 'Antibiotic-এর সম্পূর্ণ কোর্স শেষ করুন',
    'sr5-p': 'ভালো লাগলেই antibiotic বন্ধ করবেন না। ডাক্তার যদি ৭ দিনের কোর্স দিয়েছেন, সম্পূর্ণ ৭ দিন খান। অর্ধেক কোর্সে ব্যাকটেরিয়া মরে না, বরং resistant হয়ে যায়।',
    'sr6-t': 'Pharmacist-কে প্রশ্ন করুন',
    'sr6-p': 'Pharmacist শুধু ওষুধ বিক্রি করেন না — তারা প্রশিক্ষিত professional। ওষুধের পার্শ্বপ্রতিক্রিয়া, ডোজ, বা interaction নিয়ে যেকোনো প্রশ্ন করুন। তারা সাহায্য করতে প্রস্তুত।',
    'dos-title': 'যা করবেন', 'donts-title': 'যা করবেন না',
    'do1': 'ডাক্তারের prescription মেনে চলুন', 'do2': 'Pharmacist-এর পরামর্শ নিন',
    'do3': 'ওষুধের পুরো কোর্স শেষ করুন', 'do4': 'মেয়াদ দেখে ওষুধ কিনুন',
    'do5': 'পার্শ্বপ্রতিক্রিয়া হলে ডাক্তারকে জানান', 'do6': 'ওষুধ ঠাণ্ডা ও শুষ্ক জায়গায় রাখুন',
    'do7': 'অ্যালার্জি থাকলে ডাক্তারকে আগে বলুন',
    'dont1': 'ডাক্তার ছাড়া antibiotic শুরু করবেন না', 'dont2': 'মাঝপথে ওষুধ বন্ধ করবেন না',
    'dont3': 'অন্যের ওষুধ নিজে নেবেন না', 'dont4': 'মেয়াদ উত্তীর্ণ ওষুধ খাবেন না',
    'dont5': 'বাথরুম বা রান্নাঘরে ওষুধ রাখবেন না', 'dont6': 'একসাথে অনেক ধরনের ওষুধ নেবেন না',
    'dont7': 'বাচ্চাদের নাগালে ওষুধ রাখবেন না',
    'gen-title': 'Generic vs Brand — পার্থক্য কী?',
    'gen-desc': 'একই ওষুধ ভিন্ন নামে বিক্রি হয়। Generic নাম হলো মূল রাসায়নিকের নাম — এটা সব ব্র্যান্ডে একই কাজ করে।',
    'gc1': 'Paracetamol (Generic)', 'gc1b': 'Napa, Ace, Renova, Tylenol, Panadol', 'gc1c': 'একই ওষুধ, আলাদা ব্র্যান্ড নাম',
    'gc2': 'Omeprazole (Generic)', 'gc2b': 'Omez, Losec, Prilosec, Seclo', 'gc2c': 'সস্তা generic নিলেও একই কাজ হয়',
    'gc3': 'Cetirizine (Generic)', 'gc3b': 'Alatrol, Cetrizin, Zyrtec, Allegra', 'gc3c': 'Pharmacist-কে generic চাইতে পারেন',
    'fq-title': 'সবচেয়ে বেশি জিজ্ঞাসিত প্রশ্ন', 'fq-desc': 'মানুষ যে প্রশ্নগুলো সবচেয়ে বেশি করে — সহজ ভাষায় উত্তর।',
    'fq1-q': '<span class="faq-badge badge-danger"><i class="fi fi-sr-triangle-warning"></i> Antibiotic</span>ভালো লাগলেই কি antibiotic বন্ধ করা যাবে?',
    'fq1-a': 'না, একদমই না। ডাক্তার যদি ৫ দিনের কোর্স দিয়েছেন, ৩ দিনেই ভালো লাগলেও বাকি ২ দিন খান। কারণ — ৩ দিনে ৯০% ব্যাকটেরিয়া মরে যায়, কিন্তু বাকি ১০% সবচেয়ে শক্তিশালী। এদের মেরে না ফেললে পরে antibiotic কাজ করবে না (Antibiotic Resistance)।',
    'fq2-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-capsule"></i> Painkiller</span>ব্যথা বেশি হলে কি ২টা Painkiller একসাথে খেলে বেশি কাজ হবে?',
    'fq2-a': 'না! একই ধরনের ২টা painkiller (যেমন ২টা paracetamol বা paracetamol + ibuprofen) একসাথে খাওয়া বিপজ্জনক। এতে লিভার বা পেটের মারাত্মক ক্ষতি হতে পারে। বেশি ব্যথায় ডোজ বাড়ানোর আগে ডাক্তারের সাথে কথা বলুন।',
    'fq3-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-flower"></i> জন্মনিয়ন্ত্রণ</span>জন্মনিয়ন্ত্রণ পিল একটি মিস হলে কী করবো?',
    'fq3-a': 'যদি ২৪ ঘণ্টার মধ্যে মনে পড়ে তাহলে একটি পিল খান। যদি ২৪ ঘণ্টার বেশি হয়ে যায়, তাহলে সেই পিল বাদ দিন এবং পরের দিন থেকে স্বাভাবিক সময়ে খান। কিন্তু এই সময় অতিরিক্ত সতর্ক থাকুন। ২টা পিল মিস হলে তৎক্ষণিক ডাক্তারের পরামর্শ নিন।',
    'fq4-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-alarm-clock"></i> মেয়াদ</span>জরুরি অবস্থায় মেয়াদ উত্তীর্ণ ওষুধ খাওয়া কি নিরাপদ?',
    'fq4-a': 'বেশিরভাগ solid ট্যাবলেট কিছুটা কম কার্যকর হয় — সাথে সাথে বিষাক্ত হয় না। কিন্তু তরল antibiotic, eye drop, insulin ও injection মেয়াদ শেষ হলে বিপজ্জনক হতে পারে। যতটা সম্ভব তাজা ওষুধ ব্যবহার করুন এবং মেয়াদ উত্তীর্ণ ওষুধ ঘরে না রেখে ফেলে দিন।',
    'fq5-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-comment-alt"></i> Generic</span>Pharmacist ভিন্ন ব্র্যান্ড দিলে কি একই কাজ হবে?',
    'fq5-a': 'হ্যাঁ, সাধারণত। ডাক্তার Napa লিখলেও Pharmacist Ace বা Renova দিলে একই কাজ হয় — কারণ সবার মূল রাসায়নিক Paracetamol। এই ওষুধগুলোকে Generic বলে। তবে কিছু বিশেষ ওষুধের ক্ষেত্রে (যেমন thyroid, seizure) ব্র্যান্ড বদলানো উচিত নয়। সন্দেহ হলে pharmacist-কে জিজ্ঞেস করুন।',
    'fq6-q': '<span class="faq-badge badge-warn"><i class="fi fi-rr-moon"></i> ঘুমের ওষুধ</span>ঘুমের ওষুধ কি নিরাপদ?',
    'fq6-a': 'ঘুমের ওষুধ স্বল্পমেয়াদে ডাক্তারের prescription-এ নিরাপদ। কিন্তু দীর্ঘমেয়াদে (২ সপ্তাহের বেশি) আসক্তি তৈরি হয়। হঠাৎ বন্ধ করলে withdrawal হয়। ঘুমের সমস্যার স্থায়ী সমাধানের জন্য জীবনযাত্রা পরিবর্তন করুন ও ডাক্তারের পরামর্শ নিন।',
    'fq7-q': '<span class="faq-badge badge-safe"><i class="fi fi-rr-heart-rate"></i> গ্যাস্ট্রিক</span>গ্যাস্ট্রিকের ওষুধ কি প্রতিদিন খাওয়া ঠিক?',
    'fq7-a': 'না, প্রতিদিন খাওয়া ঠিক নয়। প্রয়োজনে সর্বোচ্চ ৪-৮ সপ্তাহ খাওয়া যায়। এর বেশি খেলে হাড় দুর্বল হওয়া, Vitamin B12 কমে যাওয়া এবং কিডনি সমস্যা হতে পারে। জীবনযাত্রা পরিবর্তন করুন — মশলাদার খাবার কমান, সময়মতো খান।',
    'fq8-q': '<span class="faq-badge badge-danger"><i class="fi fi-rr-head-side-cough"></i> অ্যালার্জি</span>অ্যালার্জির ওষুধ খেলে কি গাড়ি চালানো যাবে?',
    'fq8-a': 'পুরানো antihistamine (যেমন Phenergan, Avil, Chlorpheniramine) খেলে ঘুম আসে — গাড়ি চালানো বিপজ্জনক। নতুন antihistamine (Cetirizine, Loratadine, Fexofenadine) তুলনামূলকভাবে কম ঘুমের ভাব দেয়। তবে যেকোনো অ্যালার্জি ওষুধ খাওয়ার পরে নিজের অবস্থা বুঝে গাড়ি চালান।',
    'ab-tag': 'আমাদের সম্পর্কে', 'ab-title': 'এই উদ্যোগের পেছনের গল্প',
    'founder-name': 'হাবেবা হোসাইন', 'founder-role': 'ফার্মেসি শিক্ষার্থী ও Fellow',
    'ab-p1': 'বাংলাদেশের অধিকাংশ কর্মজীবী মানুষ — গার্মেন্টস কর্মী, রিকশাচালক, দোকানদার, গৃহকর্মী — ওষুধ সম্পর্কে সঠিক তথ্য জানেন না। তারা প্রায়ই পাশের দোকান থেকে নিজেই ওষুধ কিনে খান, ডাক্তারের কাছে যাওয়ার সময় ও টাকা দুটোই নেই।',
    'ab-p2': 'ফার্মেসিতে পড়তে গিয়ে দেখলাম, এই মানুষগুলো শুধু একটু সঠিক তথ্য পেলেও অনেক বিপদ এড়াতে পারতেন। Antibiotic resistance, overdose, মেয়াদ উত্তীর্ণ ওষুধ — এই সমস্যাগুলো শুধু জ্ঞানের অভাবেই হচ্ছে।',
    'ab-p3': 'এই ওয়েবসাইটটি তৈরি হয়েছে সেই মানুষগুলোর জন্য। সহজ বাংলায়, সরল ভাষায় — যাতে যে কেউ বুঝতে পারেন। স্থানীয় ফার্মেসিতে QR code পোস্টার থাকবে — ওষুধ কিনতে গিয়েই স্ক্যান করে জানতে পারবেন।',
    'fel-title': 'Fellowship Program — রাউন্ড ২',
    'fel-desc': 'এই প্রকল্পটি একটি Fellowship Program-এর অংশ হিসেবে তৈরি হয়েছে। লক্ষ্য: কর্মজীবী মানুষের মধ্যে ওষুধ সচেতনতা বাড়ানো।',
    'mis-title': 'আমাদের লক্ষ্য',
    'mp1': 'সহজ ভাষায় ওষুধের সঠিক তথ্য দেওয়া',
    'mp2': 'Antibiotic-এর অপব্যবহার ও resistance নিয়ে সচেতনতা',
    'mp3': 'QR code-এর মাধ্যমে ফার্মেসিতে সরাসরি তথ্য পৌঁছে দেওয়া',
    'mp4': 'মেয়াদ উত্তীর্ণ ওষুধের বিপদ থেকে মানুষকে রক্ষা করা',
    'mp5': 'কর্মজীবী ও কম শিক্ষিত মানুষের স্বাস্থ্য সুরক্ষা',
    'cont-title': 'যোগাযোগ করুন',
    'cont-role': 'ফার্মেসি শিক্ষার্থী, বাংলাদেশ',
    'disclaimer-text': 'এই ওয়েবসাইটটি শুধু সচেতনতার জন্য। চিকিৎসার জন্য সবসময় যোগ্য ডাক্তারের পরামর্শ নিন।',
    'qr-cta-title': 'QR Code পোস্টার',
    'qr-cta-desc': 'স্থানীয় ফার্মেসিতে এই পোস্টার থাকবে। স্ক্যান করলে সরাসরি এই ওয়েবসাইটে আসা যাবে।',
    'qr-btn': '<i class="fi fi-rr-smartphone"></i> QR Code দেখুন',
    'qr-title': 'ফার্মেসি পোস্টার QR Code',
    'qr-desc': 'নিচের QR Code-টি স্ক্যান করুন বা প্রিন্ট করে ফার্মেসিতে লাগান।',
    'poster-head': '<i class="fi fi-rr-document" style="margin-right:6px;"></i> পোস্টারের লেখা',
    'poster-line1': '<i class="fi fi-rr-capsule" style="margin-right:4px;"></i> ওষুধ কিনছেন?',
    'poster-line2': 'সঠিকভাবে ব্যবহার করুন।<br>এই QR code স্ক্যান করুন এবং বিনামূল্যে জানুন।',
    'poster-cta': 'ওষুধটা কী বস? | ওষুধ জানি, স্বাস্থ্য পাই',
    'qr-caption': 'এই QR Code স্ক্যান করলে সরাসরি এই ওয়েবসাইটে আসা যাবে।',
    'dl-btn': '<i class="fi fi-rr-download"></i> QR ডাউনলোড করুন',
    'print-btn': '<i class="fi fi-rr-print"></i> প্রিন্ট করুন',
    'ft-desc': 'বাংলাদেশের কর্মজীবী মানুষের জন্য ওষুধ সচেতনতার একটি উদ্যোগ। সহজ ভাষায়, বিনামূল্যে।',
    'fl1': 'হোম', 'fl2': 'ওষুধ', 'fl3': 'মেয়াদ', 'fl4': 'নিরাপত্তা', 'fl5': 'প্রশ্নোত্তর',
    'fl6': 'সম্পর্কে', 'fl7': 'QR Code',
    'ft-disclaimer': '<i class="fi fi-sr-triangle-warning"></i> এই ওয়েবসাইটটি শুধু সচেতনতার জন্য তৈরি। চিকিৎসার জন্য সবসময় যোগ্য ডাক্তার বা pharmacist-এর পরামর্শ নিন।',
  },"""

if old_bn_block in content:
    content = content.replace(old_bn_block, new_bn_block)
    print("SUCCESS: bn translations replaced with proper Bengali script.")
else:
    print("ERROR: Could not find the bn block to replace!")
    # Try to find how many chars match
    for i in range(min(len(old_bn_block), len(content))):
        idx = content.find(old_bn_block[:i])
        if idx == -1:
            print(f"Match fails at character {i}: expected '{old_bn_block[i-1:i+10]}' ...")
            print(f"Context around position: ...{content[idx-5:idx+50]}...")
            break

with open(r'f:\E\Downloads\YUMNA\oshudh-ki-boss.html', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"File size: {len(content)} chars")
